<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Chapter 10 Statistical inference</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1>Chapter 10 Statistical inference</h1>
<blockquote>原文：<a href="https://datasciencebook.ca/inference.html">https://datasciencebook.ca/inference.html</a></blockquote>
<div id="inference" class="section level1 hasAnchor" number="10">

<div id="overview-9" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Overview<a href="inference.html#overview-9" class="anchor-section" aria-label="Anchor link to header"/></h2>
<p>A typical data analysis task in practice is to draw conclusions about some
unknown aspect of a population of interest based on observed data sampled from
that population; we typically do not get data on the <em>entire</em> population. Data
analysis questions regarding how summaries, patterns, trends, or relationships
in a data set extend to the wider population are called <em>inferential
questions</em>. This chapter will start with the fundamental ideas of sampling from
populations and then introduce two common techniques in statistical inference:
<em>point estimation</em> and <em>interval estimation</em>.</p>
</div>
<div id="chapter-learning-objectives-9" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Chapter learning objectives<a href="inference.html#chapter-learning-objectives-9" class="anchor-section" aria-label="Anchor link to header"/></h2>
<p>By the end of the chapter, readers will be able to do the following:</p>
<ul>
<li>Describe real-world examples of questions that can be answered with statistical inference.</li>
<li>Define common population parameters (e.g., mean, proportion, standard deviation) that are often estimated using sampled data, and estimate these from a sample.</li>
<li>Define the following statistical sampling terms: population, sample, population parameter, point estimate, and sampling distribution.</li>
<li>Explain the difference between a population parameter and a sample point estimate.</li>
<li>Use R to draw random samples from a finite population.</li>
<li>Use R to create a sampling distribution from a finite population.</li>
<li>Describe how sample size influences the sampling distribution.</li>
<li>Define bootstrapping.</li>
<li>Use R to create a bootstrap distribution to approximate a sampling distribution.</li>
<li>Contrast the bootstrap and sampling distributions.</li>
</ul>
</div>
<div id="why-do-we-need-sampling" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Why do we need sampling?<a href="inference.html#why-do-we-need-sampling" class="anchor-section" aria-label="Anchor link to header"/></h2>
<p>We often need to understand how quantities we observe in a subset
of data relate to the same quantities in the broader population. For example, suppose a
retailer is considering selling iPhone accessories, and they want to estimate
how big the market might be. Additionally, they want to strategize how they can
market their products on North American college and university campuses. This
retailer might formulate the following question:</p>
<p><em>What proportion of all undergraduate students in North America own an iPhone?</em></p>
<p>In the above question, we are interested in making a conclusion about <em>all</em>
undergraduate students in North America; this is referred to as the <strong>population</strong>. In
general, the population is the complete collection of individuals or cases we
are interested in studying. Further, in the above question, we are interested
in computing a quantity—the proportion of iPhone owners—based on
the entire population. This proportion is referred to as a <strong>population parameter</strong>. In
general, a population parameter is a numerical characteristic of the entire
population. To compute this number in the example above, we would need to ask
every single undergraduate in North America whether they own an iPhone. In
practice, directly computing population parameters is often time-consuming and
costly, and sometimes impossible.</p>
<p>A more practical approach would be to make measurements for a <strong>sample</strong>, i.e., a
subset of individuals collected from the population. We can then compute a
<strong>sample estimate</strong>—a numerical characteristic of the sample—that
estimates the population parameter. For example, suppose we randomly selected
ten undergraduate students across North America (the sample) and computed the
proportion of those students who own an iPhone (the sample estimate). In that
case, we might suspect that proportion is a reasonable estimate of the
proportion of students who own an iPhone in the entire population. Figure
<a href="inference.html#fig:11-population-vs-sample">10.1</a> illustrates this process.
In general, the process of using a sample to make a conclusion about the
broader population from which it is taken is referred to as <strong>statistical inference</strong>.
</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:11-population-vs-sample"/>
<img src="../Images/71bd78f2538640b97b741e99b65b9a15.png" alt="The process of using a sample from a broader population to obtain a point estimate of a population parameter. In this case, a sample of 10 individuals yielded 6 who own an iPhone, resulting in an estimated population proportion of 60% iPhone owners. The actual population proportion in this example illustration is 53.8%." width="100%" data-original-src="https://datasciencebook.ca/img/inference/population_vs_sample.png"/>
<p class="caption">
Figure 10.1: The process of using a sample from a broader population to obtain a point estimate of a population parameter. In this case, a sample of 10 individuals yielded 6 who own an iPhone, resulting in an estimated population proportion of 60% iPhone owners. The actual population proportion in this example illustration is 53.8%.
</p>
</div>
<p>Note that proportions are not the <em>only</em> kind of population parameter we might
be interested in. For example, suppose an undergraduate student studying at the University
of British Columbia in Canada is looking for an apartment
to rent. They need to create a budget, so they want to know about
studio apartment rental prices in Vancouver. This student might
formulate the question:</p>
<p><em>What is the average price per month of studio apartment rentals in Vancouver?</em></p>
<p>In this case, the population consists of all studio apartment rentals in Vancouver, and the
population parameter is the <em>average price per month</em>. Here we used the average
as a measure of the center to describe the “typical value” of studio apartment
rental prices. But even within this one example, we could also be interested in
many other population parameters. For instance, we know that not every studio
apartment rental in Vancouver will have the same price per month. The student
might be interested in how much monthly prices vary and want to find a measure
of the rentals’ spread (or variability), such as the standard deviation. Or perhaps the
student might be interested in the fraction of studio apartment rentals that
cost more than $1000 per month. The question we want to answer will help us
determine the parameter we want to estimate. If we were somehow able to observe
the whole population of studio apartment rental offerings in Vancouver, we
could compute each of these numbers exactly; therefore, these are all
population parameters. There are many kinds of observations and population
parameters that you will run into in practice, but in this chapter, we will
focus on two settings:</p>
<ol style="list-style-type: decimal">
<li>Using categorical observations to estimate the proportion of a category</li>
<li>Using quantitative observations to estimate the average (or mean)</li>
</ol>
</div>
<div id="sampling-distributions" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> Sampling distributions<a href="inference.html#sampling-distributions" class="anchor-section" aria-label="Anchor link to header"/></h2>
<div id="sampling-distributions-for-proportions" class="section level3 hasAnchor" number="10.4.1">
<h3><span class="header-section-number">10.4.1</span> Sampling distributions for proportions<a href="inference.html#sampling-distributions-for-proportions" class="anchor-section" aria-label="Anchor link to header"/></h3>
<p>We will look at an example using data from
<a href="http://insideairbnb.com/">Inside Airbnb</a> <span class="citation">(<a href="#ref-insideairbnb">Cox n.d.</a>)</span>. Airbnb is an online
marketplace for arranging vacation rentals and places to stay. The data set
contains listings for Vancouver, Canada, in September 2020. Our data
includes an ID number, neighborhood, type of room, the number of people the
rental accommodates, number of bathrooms, bedrooms, beds, and the price per
night.</p>
<!--
airbnb <- read_csv("data/listings.csv") |>
  select(id, neighborhood = neighborhood_cleansed, room_type, accommodates, bathrooms = bathrooms_text, bedrooms, beds, price) |>
  mutate(price = as.numeric(str_remove(price, "[$]"))) |>
  na.omit()
airbnb <- airbnb |>
  mutate(id = 1:nrow(airbnb))
-->
<p/>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="inference.html#cb463-1" tabindex="-1"/><span class="fu">library</span>(tidyverse)</span>
<span id="cb463-2"><a href="inference.html#cb463-2" tabindex="-1"/></span>
<span id="cb463-3"><a href="inference.html#cb463-3" tabindex="-1"/><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb463-4"><a href="inference.html#cb463-4" tabindex="-1"/></span>
<span id="cb463-5"><a href="inference.html#cb463-5" tabindex="-1"/>airbnb <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/listings.csv"</span>)</span>
<span id="cb463-6"><a href="inference.html#cb463-6" tabindex="-1"/>airbnb</span></code></pre></div>
<pre><code>## # A tibble: 4,594 × 8
##       id neighbourhood     room_type accommodates bathrooms bedrooms  beds price
##    &lt;dbl&gt; &lt;chr&gt;             &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1     1 Downtown          Entire h…            5 2 baths          2     2   150
##  2     2 Downtown Eastside Entire h…            4 2 baths          2     2   132
##  3     3 West End          Entire h…            2 1 bath           1     1    85
##  4     4 Kensington-Cedar… Entire h…            2 1 bath           1     0   146
##  5     5 Kensington-Cedar… Entire h…            4 1 bath           1     2   110
##  6     6 Hastings-Sunrise  Entire h…            4 1 bath           2     3   195
##  7     7 Renfrew-Collingw… Entire h…            8 3 baths          4     5   130
##  8     8 Mount Pleasant    Entire h…            2 1 bath           1     1    94
##  9     9 Grandview-Woodla… Private …            2 1 privat…        1     1    79
## 10    10 West End          Private …            2 1 privat…        1     1    75
## # ℹ 4,584 more rows</code></pre>
<p>Suppose the city of Vancouver wants information about Airbnb rentals to help
plan city bylaws, and they want to know how many Airbnb places are listed as
entire homes and apartments (rather than as private or shared rooms). Therefore
they may want to estimate the true proportion of all Airbnb listings where the
“type of place” is listed as “entire home or apartment.” Of course, we usually
do not have access to the true population, but here let’s imagine (for learning
purposes) that our data set represents the population of all Airbnb rental
listings in Vancouver, Canada. We can find the proportion of listings where
<code>room_type == "Entire home/apt"</code>.
</p>
<div class="sourceCode" id="cb465"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb465-1"><a href="inference.html#cb465-1" tabindex="-1"/>airbnb <span class="sc">|&gt;</span></span>
<span id="cb465-2"><a href="inference.html#cb465-2" tabindex="-1"/>  <span class="fu">summarize</span>(</span>
<span id="cb465-3"><a href="inference.html#cb465-3" tabindex="-1"/>    <span class="at">n =</span>  <span class="fu">sum</span>(room_type <span class="sc">==</span> <span class="st">"Entire home/apt"</span>),</span>
<span id="cb465-4"><a href="inference.html#cb465-4" tabindex="-1"/>    <span class="at">proportion =</span> <span class="fu">sum</span>(room_type <span class="sc">==</span> <span class="st">"Entire home/apt"</span>) <span class="sc">/</span> <span class="fu">nrow</span>(airbnb)</span>
<span id="cb465-5"><a href="inference.html#cb465-5" tabindex="-1"/>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##       n proportion
##   &lt;int&gt;      &lt;dbl&gt;
## 1  3434      0.747</code></pre>
<p>We can see that the proportion of <code>Entire home/apt</code> listings in
the data set is 0.747. This
value, 0.747, is the population parameter. Remember, this
parameter value is usually unknown in real data analysis problems, as it is
typically not possible to make measurements for an entire population.</p>
<p>Instead, perhaps we can approximate it with a small subset of data!
To investigate this idea, let’s try randomly selecting 40 listings (<em>i.e.,</em> taking a random sample of
size 40 from our population), and computing the proportion for that sample.
We will use the <code>rep_sample_n</code> function from the <code>infer</code>
package to take the sample. The arguments of <code>rep_sample_n</code> are (1) the data frame to
sample from, and (2) the size of the sample to take.</p>
<div class="sourceCode" id="cb467"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb467-1"><a href="inference.html#cb467-1" tabindex="-1"/><span class="fu">library</span>(infer)</span>
<span id="cb467-2"><a href="inference.html#cb467-2" tabindex="-1"/></span>
<span id="cb467-3"><a href="inference.html#cb467-3" tabindex="-1"/>sample_1 <span class="ot">&lt;-</span> <span class="fu">rep_sample_n</span>(<span class="at">tbl =</span> airbnb, <span class="at">size =</span> <span class="dv">40</span>)</span>
<span id="cb467-4"><a href="inference.html#cb467-4" tabindex="-1"/></span>
<span id="cb467-5"><a href="inference.html#cb467-5" tabindex="-1"/>airbnb_sample_1 <span class="ot">&lt;-</span> <span class="fu">summarize</span>(sample_1,</span>
<span id="cb467-6"><a href="inference.html#cb467-6" tabindex="-1"/>  <span class="at">n =</span> <span class="fu">sum</span>(room_type <span class="sc">==</span> <span class="st">"Entire home/apt"</span>),</span>
<span id="cb467-7"><a href="inference.html#cb467-7" tabindex="-1"/>  <span class="at">prop =</span> <span class="fu">sum</span>(room_type <span class="sc">==</span> <span class="st">"Entire home/apt"</span>) <span class="sc">/</span> <span class="dv">40</span></span>
<span id="cb467-8"><a href="inference.html#cb467-8" tabindex="-1"/>)</span>
<span id="cb467-9"><a href="inference.html#cb467-9" tabindex="-1"/></span>
<span id="cb467-10"><a href="inference.html#cb467-10" tabindex="-1"/>airbnb_sample_1</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   replicate     n  prop
##       &lt;int&gt; &lt;int&gt; &lt;dbl&gt;
## 1         1    28   0.7</code></pre>
<p>Here we see that the proportion of entire home/apartment listings in this
random sample is 0.7. Wow—that’s close to our
true population value! But remember, we computed the proportion using a random sample of size 40.
This has two consequences. First, this value is only an <em>estimate</em>, i.e., our best guess
of our population parameter using this sample.
Given that we are estimating a single value here, we often
refer to it as a <strong>point estimate</strong>. Second, since the sample was random,
if we were to take <em>another</em> random sample of size 40 and compute the proportion for that sample,
we would not get the same answer:</p>
<div class="sourceCode" id="cb469"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb469-1"><a href="inference.html#cb469-1" tabindex="-1"/>sample_2 <span class="ot">&lt;-</span> <span class="fu">rep_sample_n</span>(airbnb, <span class="at">size =</span> <span class="dv">40</span>)</span>
<span id="cb469-2"><a href="inference.html#cb469-2" tabindex="-1"/></span>
<span id="cb469-3"><a href="inference.html#cb469-3" tabindex="-1"/>airbnb_sample_2 <span class="ot">&lt;-</span> <span class="fu">summarize</span>(sample_2,</span>
<span id="cb469-4"><a href="inference.html#cb469-4" tabindex="-1"/>  <span class="at">n =</span> <span class="fu">sum</span>(room_type <span class="sc">==</span> <span class="st">"Entire home/apt"</span>),</span>
<span id="cb469-5"><a href="inference.html#cb469-5" tabindex="-1"/>  <span class="at">prop =</span> <span class="fu">sum</span>(room_type <span class="sc">==</span> <span class="st">"Entire home/apt"</span>) <span class="sc">/</span> <span class="dv">40</span></span>
<span id="cb469-6"><a href="inference.html#cb469-6" tabindex="-1"/>)</span>
<span id="cb469-7"><a href="inference.html#cb469-7" tabindex="-1"/></span>
<span id="cb469-8"><a href="inference.html#cb469-8" tabindex="-1"/>airbnb_sample_2</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   replicate     n  prop
##       &lt;int&gt; &lt;int&gt; &lt;dbl&gt;
## 1         1    35 0.875</code></pre>
<p>Confirmed! We get a different value for our estimate this time.
That means that our point estimate might be unreliable. Indeed, estimates vary from sample to
sample due to <strong>sampling variability</strong>. But just how much
should we expect the estimates of our random samples to vary?
Or in other words, how much can we really trust our point estimate based on a single sample?</p>
<p>To understand this, we will simulate many samples (much more than just two)
of size 40 from our population of listings and calculate the proportion of
entire home/apartment listings in each sample. This simulation will create
many sample proportions, which we can visualize using a histogram. The
distribution of the estimate for all possible samples of a given size (which we
commonly refer to as <span class="math inline">\(n\)</span>) from a population is called
a <strong>sampling distribution</strong>. The sampling distribution will help us see how much we would
expect our sample proportions from this population to vary for samples of size 40.</p>
<p>We again use the <code>rep_sample_n</code> to take samples of size 40 from our
population of Airbnb listings. But this time we set the <code>reps</code> argument to 20,000 to specify
that we want to take 20,000 samples of size 40.
</p>
<div class="sourceCode" id="cb471"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb471-1"><a href="inference.html#cb471-1" tabindex="-1"/>samples <span class="ot">&lt;-</span> <span class="fu">rep_sample_n</span>(airbnb, <span class="at">size =</span> <span class="dv">40</span>, <span class="at">reps =</span> <span class="dv">20000</span>)</span>
<span id="cb471-2"><a href="inference.html#cb471-2" tabindex="-1"/>samples</span></code></pre></div>
<pre><code>## # A tibble: 800,000 × 9
## # Groups:   replicate [20,000]
##    replicate    id neighbourhood room_type accommodates bathrooms bedrooms  beds
##        &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;         &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;
##  1         1  4403 Downtown      Entire h…            2 1 bath           1     1
##  2         1   902 Kensington-C… Private …            2 1 shared…        1     1
##  3         1  3808 Hastings-Sun… Entire h…            6 1.5 baths        1     3
##  4         1   561 Kensington-C… Entire h…            6 1 bath           2     2
##  5         1  3385 Mount Pleasa… Entire h…            4 1 bath           1     1
##  6         1  4232 Shaughnessy   Entire h…            6 1.5 baths        2     2
##  7         1  1169 Downtown      Entire h…            3 1 bath           1     1
##  8         1   959 Kitsilano     Private …            1 1.5 shar…        1     1
##  9         1  2171 Downtown      Entire h…            2 1 bath           1     1
## 10         1  1258 Dunbar South… Entire h…            4 1 bath           2     2
## # ℹ 799,990 more rows
## # ℹ 1 more variable: price &lt;dbl&gt;</code></pre>
<p>Notice that the column <code>replicate</code> indicates the replicate, or sample, to which
each listing belongs. Above, since by default R only prints the first few rows,
it looks like all of the listings have <code>replicate</code> set to 1. But you can
check the last few entries using the <code>tail()</code> function to verify that
we indeed created 20,000 samples (or replicates).</p>
<div class="sourceCode" id="cb473"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb473-1"><a href="inference.html#cb473-1" tabindex="-1"/><span class="fu">tail</span>(samples)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 9
## # Groups:   replicate [1]
##   replicate    id neighbourhood  room_type accommodates bathrooms bedrooms  beds
##       &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;
## 1     20000  3414 Marpole        Entire h…            4 1 bath           2     2
## 2     20000  1974 Hastings-Sunr… Private …            2 1 shared…        1     1
## 3     20000  1846 Riley Park     Entire h…            4 1 bath           2     3
## 4     20000   862 Downtown       Entire h…            5 2 baths          2     2
## 5     20000  3295 Victoria-Fras… Private …            2 1 shared…        1     1
## 6     20000   997 Dunbar Southl… Private …            1 1.5 shar…        1     1
## # ℹ 1 more variable: price &lt;dbl&gt;</code></pre>
<p>Now that we have obtained the samples, we need to compute the
proportion of entire home/apartment listings in each sample.
We first group the data by the <code>replicate</code> variable—to group the
set of listings in each sample together—and then use <code>summarize</code>
to compute the proportion in each sample.
We print both the first and last few entries of the resulting data frame
below to show that we end up with 20,000 point estimates, one for each of the 20,000 samples.</p>
<div class="sourceCode" id="cb475"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb475-1"><a href="inference.html#cb475-1" tabindex="-1"/>sample_estimates <span class="ot">&lt;-</span> samples <span class="sc">|&gt;</span></span>
<span id="cb475-2"><a href="inference.html#cb475-2" tabindex="-1"/>  <span class="fu">group_by</span>(replicate) <span class="sc">|&gt;</span></span>
<span id="cb475-3"><a href="inference.html#cb475-3" tabindex="-1"/>  <span class="fu">summarize</span>(<span class="at">sample_proportion =</span> <span class="fu">sum</span>(room_type <span class="sc">==</span> <span class="st">"Entire home/apt"</span>) <span class="sc">/</span> <span class="dv">40</span>)</span>
<span id="cb475-4"><a href="inference.html#cb475-4" tabindex="-1"/></span>
<span id="cb475-5"><a href="inference.html#cb475-5" tabindex="-1"/>sample_estimates</span></code></pre></div>
<pre><code>## # A tibble: 20,000 × 2
##    replicate sample_proportion
##        &lt;int&gt;             &lt;dbl&gt;
##  1         1             0.85 
##  2         2             0.85 
##  3         3             0.65 
##  4         4             0.7  
##  5         5             0.75 
##  6         6             0.725
##  7         7             0.775
##  8         8             0.775
##  9         9             0.7  
## 10        10             0.675
## # ℹ 19,990 more rows</code></pre>
<div class="sourceCode" id="cb477"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb477-1"><a href="inference.html#cb477-1" tabindex="-1"/><span class="fu">tail</span>(sample_estimates)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##   replicate sample_proportion
##       &lt;int&gt;             &lt;dbl&gt;
## 1     19995             0.75 
## 2     19996             0.675
## 3     19997             0.625
## 4     19998             0.75 
## 5     19999             0.875
## 6     20000             0.65</code></pre>
<p>We can now visualize the sampling distribution of sample proportions
for samples of size 40 using a histogram in Figure <a href="inference.html#fig:11-example-proportions7">10.2</a>. Keep in mind: in the real world,
we don’t have access to the full population. So we
can’t take many samples and can’t actually construct or visualize the sampling distribution.
We have created this particular example
such that we <em>do</em> have access to the full population, which lets us visualize the
sampling distribution directly for learning purposes.</p>
<div class="sourceCode" id="cb479"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb479-1"><a href="inference.html#cb479-1" tabindex="-1"/>sampling_distribution <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sample_estimates, <span class="fu">aes</span>(<span class="at">x =</span> sample_proportion)) <span class="sc">+</span></span>
<span id="cb479-2"><a href="inference.html#cb479-2" tabindex="-1"/>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">"lightgrey"</span>, <span class="at">bins =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb479-3"><a href="inference.html#cb479-3" tabindex="-1"/>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sample proportions"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb479-4"><a href="inference.html#cb479-4" tabindex="-1"/>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb479-5"><a href="inference.html#cb479-5" tabindex="-1"/></span>
<span id="cb479-6"><a href="inference.html#cb479-6" tabindex="-1"/>sampling_distribution</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:11-example-proportions7"/>
<img src="../Images/7d30d32baf49497e0049a23b01b953ea.png" alt="Sampling distribution of the sample proportion for sample size 40." width="403.2" data-original-src="https://datasciencebook.ca/_main_files/figure-html/11-example-proportions7-1.png"/>
<p class="caption">
Figure 10.2: Sampling distribution of the sample proportion for sample size 40.
</p>
</div>
<p>The sampling distribution in Figure <a href="inference.html#fig:11-example-proportions7">10.2</a> appears
to be bell-shaped, is roughly symmetric, and has one peak. It is centered
around 0.7 and the sample proportions
range from about 0.4 to about
1. In fact, we can
calculate the mean of the sample proportions. </p>
<div class="sourceCode" id="cb480"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb480-1"><a href="inference.html#cb480-1" tabindex="-1"/>sample_estimates <span class="sc">|&gt;</span></span>
<span id="cb480-2"><a href="inference.html#cb480-2" tabindex="-1"/>  <span class="fu">summarize</span>(<span class="at">mean_proportion =</span> <span class="fu">mean</span>(sample_proportion))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   mean_proportion
##             &lt;dbl&gt;
## 1           0.747</code></pre>
<p>We notice that the sample proportions are centered around the population
proportion value, 0.747! In general, the mean of
the sampling distribution should be equal to the population proportion.
This is great news because it means that the sample proportion is neither an overestimate nor an
underestimate of the population proportion.
In other words, if you were to take many samples as we did above, there is no tendency
towards over or underestimating the population proportion.
In a real data analysis setting where you just have access to your single
sample, this implies that you would suspect that your sample point estimate is
roughly equally likely to be above or below the true population proportion.</p>
</div>
<div id="sampling-distributions-for-means" class="section level3 hasAnchor" number="10.4.2">
<h3><span class="header-section-number">10.4.2</span> Sampling distributions for means<a href="inference.html#sampling-distributions-for-means" class="anchor-section" aria-label="Anchor link to header"/></h3>
<p>In the previous section, our variable of interest—<code>room_type</code>—was
<em>categorical</em>, and the population parameter was a proportion. As mentioned in
the chapter introduction, there are many choices of the population parameter
for each type of variable. What if we wanted to infer something about a
population of <em>quantitative</em> variables instead? For instance, a traveler
visiting Vancouver, Canada may wish to estimate the
population <em>mean</em> (or average) price per night of Airbnb listings. Knowing
the average could help them tell whether a particular listing is overpriced.
We can visualize the population distribution of the price per night with a histogram.</p>
<div class="sourceCode" id="cb482"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb482-1"><a href="inference.html#cb482-1" tabindex="-1"/>population_distribution <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(airbnb, <span class="fu">aes</span>(<span class="at">x =</span> price)) <span class="sc">+</span></span>
<span id="cb482-2"><a href="inference.html#cb482-2" tabindex="-1"/>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">"lightgrey"</span>) <span class="sc">+</span></span>
<span id="cb482-3"><a href="inference.html#cb482-3" tabindex="-1"/>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Price per night (dollars)"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb482-4"><a href="inference.html#cb482-4" tabindex="-1"/>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb482-5"><a href="inference.html#cb482-5" tabindex="-1"/></span>
<span id="cb482-6"><a href="inference.html#cb482-6" tabindex="-1"/>population_distribution</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:11-example-means2"/>
<img src="../Images/b04d2ed9eb23562f5e20c5201ef483e2.png" alt="Population distribution of price per night (dollars) for all Airbnb listings in Vancouver, Canada." width="432" data-original-src="https://datasciencebook.ca/_main_files/figure-html/11-example-means2-1.png"/>
<p class="caption">
Figure 10.3: Population distribution of price per night (dollars) for all Airbnb listings in Vancouver, Canada.
</p>
</div>
<p>In Figure <a href="inference.html#fig:11-example-means2">10.3</a>, we see that the population distribution
has one peak. It is also skewed (i.e., is not symmetric): most of the listings are
less than $250 per night, but a small number of listings cost much more,
creating a long tail on the histogram’s right side.
Along with visualizing the population, we can calculate the population mean,
the average price per night for all the Airbnb listings.</p>
<div class="sourceCode" id="cb483"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb483-1"><a href="inference.html#cb483-1" tabindex="-1"/>population_parameters <span class="ot">&lt;-</span> airbnb <span class="sc">|&gt;</span></span>
<span id="cb483-2"><a href="inference.html#cb483-2" tabindex="-1"/>  <span class="fu">summarize</span>(<span class="at">mean_price =</span> <span class="fu">mean</span>(price))</span>
<span id="cb483-3"><a href="inference.html#cb483-3" tabindex="-1"/></span>
<span id="cb483-4"><a href="inference.html#cb483-4" tabindex="-1"/>population_parameters</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   mean_price
##        &lt;dbl&gt;
## 1     154.51</code></pre>
<p>The price per night of all Airbnb rentals in Vancouver, BC
is $154.51, on average. This value is our
population parameter since we are calculating it using the population data. </p>
<p>Now suppose we did not have access to the population data (which is usually the
case!), yet we wanted to estimate the mean price per night. We could answer
this question by taking a random sample of as many Airbnb listings as our time
and resources allow. Let’s say we could do this for 40 listings. What would
such a sample look like? Let’s take advantage of the fact that we do have
access to the population data and simulate taking one random sample of 40
listings in R, again using <code>rep_sample_n</code>.
</p>
<div class="sourceCode" id="cb485"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb485-1"><a href="inference.html#cb485-1" tabindex="-1"/>one_sample <span class="ot">&lt;-</span> airbnb <span class="sc">|&gt;</span></span>
<span id="cb485-2"><a href="inference.html#cb485-2" tabindex="-1"/>  <span class="fu">rep_sample_n</span>(<span class="dv">40</span>)</span></code></pre></div>
<p>We can create a histogram to visualize the distribution of observations in the
sample (Figure <a href="inference.html#fig:11-example-means-sample-hist">10.4</a>), and calculate the mean
of our sample.</p>
<div class="sourceCode" id="cb486"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb486-1"><a href="inference.html#cb486-1" tabindex="-1"/>sample_distribution <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(one_sample, <span class="fu">aes</span>(price)) <span class="sc">+</span></span>
<span id="cb486-2"><a href="inference.html#cb486-2" tabindex="-1"/>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">"lightgrey"</span>) <span class="sc">+</span></span>
<span id="cb486-3"><a href="inference.html#cb486-3" tabindex="-1"/>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Price per night (dollars)"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb486-4"><a href="inference.html#cb486-4" tabindex="-1"/>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb486-5"><a href="inference.html#cb486-5" tabindex="-1"/></span>
<span id="cb486-6"><a href="inference.html#cb486-6" tabindex="-1"/>sample_distribution</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:11-example-means-sample-hist"/>
<img src="../Images/c27ee83f432ed1d1b5c6ee1bfdb17372.png" alt="Distribution of price per night (dollars) for sample of 40 Airbnb listings." width="432" data-original-src="https://datasciencebook.ca/_main_files/figure-html/11-example-means-sample-hist-1.png"/>
<p class="caption">
Figure 10.4: Distribution of price per night (dollars) for sample of 40 Airbnb listings.
</p>
</div>
<div class="sourceCode" id="cb487"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb487-1"><a href="inference.html#cb487-1" tabindex="-1"/>estimates <span class="ot">&lt;-</span> one_sample <span class="sc">|&gt;</span></span>
<span id="cb487-2"><a href="inference.html#cb487-2" tabindex="-1"/>  <span class="fu">summarize</span>(<span class="at">mean_price =</span> <span class="fu">mean</span>(price))</span>
<span id="cb487-3"><a href="inference.html#cb487-3" tabindex="-1"/></span>
<span id="cb487-4"><a href="inference.html#cb487-4" tabindex="-1"/>estimates</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   replicate mean_price
##       &lt;int&gt;      &lt;dbl&gt;
## 1         1     155.80</code></pre>
<p>The average value of the sample of size 40
is $155.80. This
number is a point estimate for the mean of the full population.
Recall that the population mean was
$154.51. So our estimate was fairly close to
the population parameter: the mean was about
0.8%
off. Note that we usually cannot compute the estimate’s accuracy in practice
since we do not have access to the population parameter; if we did, we wouldn’t
need to estimate it!</p>
<p>Also, recall from the previous section that the point estimate can vary; if we
took another random sample from the population, our estimate’s value might
change. So then, did we just get lucky with our point estimate above? How much
does our estimate vary across different samples of size 40 in this example?
Again, since we have access to the population, we can take many samples and
plot the sampling distribution of sample means for samples of size 40 to
get a sense for this variation. In this case, we’ll use 20,000 samples of size
40.</p>
<div class="sourceCode" id="cb489"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb489-1"><a href="inference.html#cb489-1" tabindex="-1"/>samples <span class="ot">&lt;-</span> <span class="fu">rep_sample_n</span>(airbnb, <span class="at">size =</span> <span class="dv">40</span>, <span class="at">reps =</span> <span class="dv">20000</span>)</span>
<span id="cb489-2"><a href="inference.html#cb489-2" tabindex="-1"/>samples</span></code></pre></div>
<pre><code>## # A tibble: 800,000 × 9
## # Groups:   replicate [20,000]
##    replicate    id neighbourhood room_type accommodates bathrooms bedrooms  beds
##        &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;         &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;
##  1         1  1177 Downtown      Entire h…            4 2 baths          2     2
##  2         1  4063 Downtown      Entire h…            2 1 bath           1     1
##  3         1  2641 Kitsilano     Private …            1 1 shared…        1     1
##  4         1  1941 West End      Entire h…            2 1 bath           1     1
##  5         1  2431 Mount Pleasa… Entire h…            2 1 bath           1     1
##  6         1  1871 Arbutus Ridge Entire h…            4 1 bath           2     2
##  7         1  2557 Marpole       Private …            3 1 privat…        1     2
##  8         1  3534 Downtown      Entire h…            2 1 bath           1     1
##  9         1  4379 Downtown      Entire h…            4 1 bath           1     0
## 10         1  2161 Downtown      Entire h…            4 2 baths          2     2
## # ℹ 799,990 more rows
## # ℹ 1 more variable: price &lt;dbl&gt;</code></pre>
<p>Now we can calculate the sample mean for each replicate and plot the sampling
distribution of sample means for samples of size 40.</p>
<div class="sourceCode" id="cb491"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb491-1"><a href="inference.html#cb491-1" tabindex="-1"/>sample_estimates <span class="ot">&lt;-</span> samples <span class="sc">|&gt;</span></span>
<span id="cb491-2"><a href="inference.html#cb491-2" tabindex="-1"/>  <span class="fu">group_by</span>(replicate) <span class="sc">|&gt;</span></span>
<span id="cb491-3"><a href="inference.html#cb491-3" tabindex="-1"/>  <span class="fu">summarize</span>(<span class="at">mean_price =</span> <span class="fu">mean</span>(price))</span>
<span id="cb491-4"><a href="inference.html#cb491-4" tabindex="-1"/></span>
<span id="cb491-5"><a href="inference.html#cb491-5" tabindex="-1"/>sample_estimates</span></code></pre></div>
<pre><code>## # A tibble: 20,000 × 2
##    replicate mean_price
##        &lt;int&gt;      &lt;dbl&gt;
##  1         1     160.06
##  2         2     173.18
##  3         3     131.20
##  4         4     176.96
##  5         5     125.65
##  6         6     148.84
##  7         7     134.82
##  8         8     137.26
##  9         9     166.11
## 10        10     157.81
## # ℹ 19,990 more rows</code></pre>
<div class="sourceCode" id="cb493"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb493-1"><a href="inference.html#cb493-1" tabindex="-1"/>sampling_distribution_40 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sample_estimates, <span class="fu">aes</span>(<span class="at">x =</span> mean_price)) <span class="sc">+</span></span>
<span id="cb493-2"><a href="inference.html#cb493-2" tabindex="-1"/>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">"lightgrey"</span>) <span class="sc">+</span></span>
<span id="cb493-3"><a href="inference.html#cb493-3" tabindex="-1"/>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sample mean price per night (dollars)"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb493-4"><a href="inference.html#cb493-4" tabindex="-1"/>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb493-5"><a href="inference.html#cb493-5" tabindex="-1"/></span>
<span id="cb493-6"><a href="inference.html#cb493-6" tabindex="-1"/>sampling_distribution_40</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:11-example-means4"/>
<img src="../Images/4fc6eca803c2f8f50905530484019536.png" alt="Sampling distribution of the sample means for sample size of 40." width="432" data-original-src="https://datasciencebook.ca/_main_files/figure-html/11-example-means4-1.png"/>
<p class="caption">
Figure 10.5: Sampling distribution of the sample means for sample size of 40.
</p>
</div>
<p>In Figure <a href="inference.html#fig:11-example-means4">10.5</a>, the sampling distribution of the mean
has one peak and is bell-shaped. Most of the estimates are between
about $140 and
$170; but there is
a good fraction of cases outside this range (i.e., where the point estimate was
not close to the population parameter). So it does indeed look like we were
quite lucky when we estimated the population mean with only
0.8% error.</p>
<p>Let’s visualize the population distribution, distribution of the sample, and
the sampling distribution on one plot to compare them in Figure
<a href="inference.html#fig:11-example-means5">10.6</a>. Comparing these three distributions, the centers
of the distributions are all around the same price (around $150). The original
population distribution has a long right tail, and the sample distribution has
a similar shape to that of the population distribution. However, the sampling
distribution is not shaped like the population or sample distribution. Instead,
it has a bell shape, and it has a lower spread than the population or sample
distributions. The sample means vary less than the individual observations
because there will be some high values and some small values in any random
sample, which will keep the average from being too extreme.
</p>
<!---

```r
sample_estimates |>
  summarize(mean_of_sample_means = mean(mean_price))
```

```
## # A tibble: 1 × 1
##   mean_of_sample_means
##                  <dbl>
## 1               154.35
```
Notice that the mean of the sample means is \$154.35. Recall that the population mean
was \$154.51.
-->
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:11-example-means5"/>
<img src="../Images/c25133e5cdba47beb200ef7815a7b24f.png" alt="Comparison of population distribution, sample distribution, and sampling distribution." width="384" data-original-src="https://datasciencebook.ca/_main_files/figure-html/11-example-means5-1.png"/>
<p class="caption">
Figure 10.6: Comparison of population distribution, sample distribution, and sampling distribution.
</p>
</div>
<p>Given that there is quite a bit of variation in the sampling distribution of
the sample mean—i.e., the point estimate that we obtain is not very
reliable—is there any way to improve the estimate? One way to improve a
point estimate is to take a <em>larger</em> sample. To illustrate what effect this
has, we will take many samples of size 20, 50, 100, and 500, and plot the
sampling distribution of the sample mean. We indicate the mean of the sampling
distribution with a vertical dashed line.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:11-example-means7"/>
<img src="../Images/15f07c8d6a883303fb9654e6e755e16b.png" alt="Comparison of sampling distributions, with mean highlighted as a vertical dashed line." width="672" data-original-src="https://datasciencebook.ca/_main_files/figure-html/11-example-means7-1.png"/>
<p class="caption">
Figure 10.7: Comparison of sampling distributions, with mean highlighted as a vertical dashed line.
</p>
</div>
<p>Based on the visualization in Figure <a href="inference.html#fig:11-example-means7">10.7</a>, three points
about the sample mean become clear. First, the mean of the sample mean (across
samples) is equal to the population mean. In other words, the sampling
distribution is centered at the population mean. Second, increasing the size of
the sample decreases the spread (i.e., the variability) of the sampling
distribution. Therefore, a larger sample size results in a more reliable point
estimate of the population parameter. And third, the distribution of the sample
mean is roughly bell-shaped. </p>
<blockquote>
<p><strong>Note:</strong> You might notice that in the <code>n = 20</code> case in Figure <a href="inference.html#fig:11-example-means7">10.7</a>,
the distribution is not <em>quite</em> bell-shaped. There is a bit of skew towards the right!
You might also notice that in the <code>n = 50</code> case and larger, that skew seems to disappear.
In general, the sampling distribution—for both means and proportions—only
becomes bell-shaped <em>once the sample size is large enough</em>.
How large is “large enough?” Unfortunately, it depends entirely on the problem at hand. But
as a rule of thumb, often a sample size of at least 20 will suffice.</p>
</blockquote>
<!--- > **Note:** If random samples of size $n$ are taken from a population, the sample mean $\bar{x}$ will be approximately Normal with mean $\mu$ and standard deviation $\frac{\sigma}{\sqrt{n}}$ as long as the sample size $n$ is large enough. $\mu$ is the population mean, $\sigma$ is the population standard deviation, $\bar{x}$ is the sample mean, and $n$ is the sample size.
> If samples are selected from a finite population as we are doing in this chapter, we should apply a finite population correction. We multiply $\frac{\sigma}{\sqrt{n}}$ by $\sqrt{\frac{N - n}{N - 1}}$ where $N$ is the population size and $n$ is the sample size. If our sample size, $n$, is small relative to the population size, this finite correction factor is less important.
--->
</div>
<div id="summary-2" class="section level3 hasAnchor" number="10.4.3">
<h3><span class="header-section-number">10.4.3</span> Summary<a href="inference.html#summary-2" class="anchor-section" aria-label="Anchor link to header"/></h3>
<ol style="list-style-type: decimal">
<li>A point estimate is a single value computed using a sample from a population (e.g., a mean or proportion).</li>
<li>The sampling distribution of an estimate is the distribution of the estimate for all possible samples of a fixed size from the same population.</li>
<li>The shape of the sampling distribution is usually bell-shaped with one peak and centered at the population mean or proportion.</li>
<li>The spread of the sampling distribution is related to the sample size. As the sample size increases, the spread of the sampling distribution decreases.</li>
</ol>
</div>
</div>
<div id="bootstrapping" class="section level2 hasAnchor" number="10.5">
<h2><span class="header-section-number">10.5</span> Bootstrapping<a href="inference.html#bootstrapping" class="anchor-section" aria-label="Anchor link to header"/></h2>
<div id="overview-10" class="section level3 hasAnchor" number="10.5.1">
<h3><span class="header-section-number">10.5.1</span> Overview<a href="inference.html#overview-10" class="anchor-section" aria-label="Anchor link to header"/></h3>
<p><em>Why all this emphasis on sampling distributions?</em></p>
<p>We saw in the previous section that we could compute a <strong>point estimate</strong> of a
population parameter using a sample of observations from the population. And
since we constructed examples where we had access to the population, we could
evaluate how accurate the estimate was, and even get a sense of how much the
estimate would vary for different samples from the population. But in real
data analysis settings, we usually have <em>just one sample</em> from our population
and do not have access to the population itself. Therefore we cannot construct
the sampling distribution as we did in the previous section. And as we saw, our
sample estimate’s value can vary significantly from the population parameter.
So reporting the point estimate from a single sample alone may not be enough.
We also need to report some notion of <em>uncertainty</em> in the value of the point
estimate.</p>
<p>Unfortunately, we cannot construct the exact sampling distribution without
full access to the population. However, if we could somehow <em>approximate</em> what
the sampling distribution would look like for a sample, we could
use that approximation to then report how uncertain our sample
point estimate is (as we did above with the <em>exact</em> sampling
distribution). There are several methods to accomplish this; in this book, we
will use the <em>bootstrap</em>. We will discuss <strong>interval estimation</strong> and
construct
<strong>confidence intervals</strong> using just a single sample from a population. A
confidence interval is a range of plausible values for our population parameter.</p>
<p>Here is the key idea. First, if you take a big enough sample, it <em>looks like</em>
the population. Notice the histograms’ shapes for samples of different sizes
taken from the population in Figure <a href="inference.html#fig:11-example-bootstrapping0">10.8</a>. We
see that the sample’s distribution looks like that of the population for a
large enough sample.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:11-example-bootstrapping0"/>
<img src="../Images/65a1c85c62a5ea1b0b50f2032d700489.png" alt="Comparison of samples of different sizes from the population." width="672" data-original-src="https://datasciencebook.ca/_main_files/figure-html/11-example-bootstrapping0-1.png"/>
<p class="caption">
Figure 10.8: Comparison of samples of different sizes from the population.
</p>
</div>
<p>In the previous section, we took many samples of the same size <em>from our
population</em> to get a sense of the variability of a sample estimate. But if our
sample is big enough that it looks like our population, we can pretend that our
sample <em>is</em> the population, and take more samples (with replacement) of the
same size from it instead! This very clever technique is
called <strong>the bootstrap</strong>. Note that by taking many samples from our single, observed
sample, we do not obtain the true sampling distribution, but rather an
approximation that we call <strong>the bootstrap distribution</strong>. </p>
<div style="page-break-after: always;"/>
<blockquote>
<p><strong>Note:</strong> We must sample <em>with</em> replacement when using the bootstrap.
Otherwise, if we had a sample of size <span class="math inline">\(n\)</span>, and obtained a sample from it of
size <span class="math inline">\(n\)</span> <em>without</em> replacement, it would just return our original sample!</p>
</blockquote>
<p>This section will explore how to create a bootstrap distribution from a single
sample using R. The process is visualized in Figure <a href="inference.html#fig:11-intro-bootstrap-image">10.9</a>.
For a sample of size <span class="math inline">\(n\)</span>, you would do the following:</p>
<ol style="list-style-type: decimal">
<li>Randomly select an observation from the original sample, which was drawn from the population.</li>
<li>Record the observation’s value.</li>
<li>Replace that observation.</li>
<li>Repeat steps 1–3 (sampling <em>with</em> replacement) until you have <span class="math inline">\(n\)</span> observations, which form a bootstrap sample.</li>
<li>Calculate the bootstrap point estimate (e.g., mean, median, proportion, slope, etc.) of the <span class="math inline">\(n\)</span> observations in your bootstrap sample.</li>
<li>Repeat steps 1–5 many times to create a distribution of point estimates (the bootstrap distribution).</li>
<li>Calculate the plausible range of values around our observed point estimate.</li>
</ol>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:11-intro-bootstrap-image"/>
<img src="../Images/5aaa2fe6e2a089e05c86f3a861a14f6a.png" alt="Overview of the bootstrap process." width="100%" data-original-src="https://datasciencebook.ca/img/inference/intro-bootstrap.jpeg"/>
<p class="caption">
Figure 10.9: Overview of the bootstrap process.
</p>
</div>
</div>
<div id="bootstrapping-in-r" class="section level3 hasAnchor" number="10.5.2">
<h3><span class="header-section-number">10.5.2</span> Bootstrapping in R<a href="inference.html#bootstrapping-in-r" class="anchor-section" aria-label="Anchor link to header"/></h3>
<p>Let’s continue working with our Airbnb example to illustrate how we might create
and use a bootstrap distribution using just a single sample from the population.
Once again, suppose we are
interested in estimating the population mean price per night of all Airbnb
listings in Vancouver, Canada, using a single sample size of 40.
Recall our point estimate was $155.80. The
histogram of prices in the sample is displayed in Figure <a href="inference.html#fig:11-bootstrapping1">10.10</a>.</p>
<div class="sourceCode" id="cb494"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb494-1"><a href="inference.html#cb494-1" tabindex="-1"/>one_sample</span></code></pre></div>
<pre><code>## # A tibble: 40 × 8
##       id neighbourhood     room_type accommodates bathrooms bedrooms  beds price
##    &lt;dbl&gt; &lt;chr&gt;             &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1  3928 Marpole           Private …            2 1 shared…        1     1    58
##  2  3013 Kensington-Cedar… Entire h…            4 1 bath           2     2   112
##  3  3156 Downtown          Entire h…            6 2 baths          2     2   151
##  4  3873 Dunbar Southlands Private …            5 1 bath           2     3   700
##  5  3632 Downtown Eastside Entire h…            6 2 baths          3     3   157
##  6   296 Kitsilano         Private …            1 1 shared…        1     1   100
##  7  3514 West End          Entire h…            2 1 bath           1     1   110
##  8   594 Sunset            Entire h…            5 1 bath           3     3   105
##  9  3305 Dunbar Southlands Entire h…            4 1 bath           1     2   196
## 10   938 Downtown          Entire h…            7 2 baths          2     3   269
## # ℹ 30 more rows</code></pre>
<div class="sourceCode" id="cb496"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb496-1"><a href="inference.html#cb496-1" tabindex="-1"/>one_sample_dist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(one_sample, <span class="fu">aes</span>(price)) <span class="sc">+</span></span>
<span id="cb496-2"><a href="inference.html#cb496-2" tabindex="-1"/>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">"lightgrey"</span>) <span class="sc">+</span></span>
<span id="cb496-3"><a href="inference.html#cb496-3" tabindex="-1"/>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Price per night (dollars)"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb496-4"><a href="inference.html#cb496-4" tabindex="-1"/>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb496-5"><a href="inference.html#cb496-5" tabindex="-1"/></span>
<span id="cb496-6"><a href="inference.html#cb496-6" tabindex="-1"/>one_sample_dist</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:11-bootstrapping1"/>
<img src="../Images/f7d9eb6a586db87c509f573b7ba89815.png" alt="Histogram of price per night (dollars) for one sample of size 40." width="432" data-original-src="https://datasciencebook.ca/_main_files/figure-html/11-bootstrapping1-1.png"/>
<p class="caption">
Figure 10.10: Histogram of price per night (dollars) for one sample of size 40.
</p>
</div>
<p>The histogram for the sample is skewed, with a few observations out to the right. The
mean of the sample is $155.80.
Remember, in practice, we usually only have this one sample from the population. So
this sample and estimate are the only data we can work with.</p>
<p>We now perform steps 1–5 listed above to generate a single bootstrap
sample in R and calculate a point estimate from that bootstrap sample. We will
use the <code>rep_sample_n</code> function as we did when we were
creating our sampling distribution. But critically, note that we now
pass <code>one_sample</code>—our single sample of size 40—as the first argument.
And since we need to sample with replacement,
we change the argument for <code>replace</code> from its default value of <code>FALSE</code> to <code>TRUE</code>.
</p>
<div class="sourceCode" id="cb497"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb497-1"><a href="inference.html#cb497-1" tabindex="-1"/>boot1 <span class="ot">&lt;-</span> one_sample <span class="sc">|&gt;</span></span>
<span id="cb497-2"><a href="inference.html#cb497-2" tabindex="-1"/>  <span class="fu">rep_sample_n</span>(<span class="at">size =</span> <span class="dv">40</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">reps =</span> <span class="dv">1</span>)</span>
<span id="cb497-3"><a href="inference.html#cb497-3" tabindex="-1"/>boot1_dist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(boot1, <span class="fu">aes</span>(price)) <span class="sc">+</span></span>
<span id="cb497-4"><a href="inference.html#cb497-4" tabindex="-1"/>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">"lightgrey"</span>) <span class="sc">+</span></span>
<span id="cb497-5"><a href="inference.html#cb497-5" tabindex="-1"/>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Price per night (dollars)"</span>, <span class="at">y =</span>  <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb497-6"><a href="inference.html#cb497-6" tabindex="-1"/>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb497-7"><a href="inference.html#cb497-7" tabindex="-1"/></span>
<span id="cb497-8"><a href="inference.html#cb497-8" tabindex="-1"/>boot1_dist</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:11-bootstrapping3"/>
<img src="../Images/88d3f9007bc1e8822121e87e397341a3.png" alt="Bootstrap distribution." width="432" data-original-src="https://datasciencebook.ca/_main_files/figure-html/11-bootstrapping3-1.png"/>
<p class="caption">
Figure 10.11: Bootstrap distribution.
</p>
</div>
<div class="sourceCode" id="cb498"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb498-1"><a href="inference.html#cb498-1" tabindex="-1"/><span class="fu">summarize</span>(boot1, <span class="at">mean_price =</span> <span class="fu">mean</span>(price))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   replicate mean_price
##       &lt;int&gt;      &lt;dbl&gt;
## 1         1     164.20</code></pre>
<p>Notice in Figure <a href="inference.html#fig:11-bootstrapping3">10.11</a> that the histogram of our bootstrap sample
has a similar shape to the original sample histogram. Though the shapes of
the distributions are similar, they are not identical. You’ll also notice that
the original sample mean and the bootstrap sample mean differ. How might that
happen? Remember that we are sampling with replacement from the original
sample, so we don’t end up with the same sample values again. We are <em>pretending</em>
that our single sample is close to the population, and we are trying to
mimic drawing another sample from the population by drawing one from our original
sample.</p>
<p>Let’s now take 20,000 bootstrap samples from the original sample (<code>one_sample</code>)
using <code>rep_sample_n</code>, and calculate the means for
each of those replicates. Recall that this assumes that <code>one_sample</code> <em>looks like</em>
our original population; but since we do not have access to the population itself,
this is often the best we can do.</p>
<div class="sourceCode" id="cb500"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb500-1"><a href="inference.html#cb500-1" tabindex="-1"/>boot20000 <span class="ot">&lt;-</span> one_sample <span class="sc">|&gt;</span></span>
<span id="cb500-2"><a href="inference.html#cb500-2" tabindex="-1"/>  <span class="fu">rep_sample_n</span>(<span class="at">size =</span> <span class="dv">40</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">reps =</span> <span class="dv">20000</span>)</span>
<span id="cb500-3"><a href="inference.html#cb500-3" tabindex="-1"/></span>
<span id="cb500-4"><a href="inference.html#cb500-4" tabindex="-1"/>boot20000</span></code></pre></div>
<pre><code>## # A tibble: 800,000 × 9
## # Groups:   replicate [20,000]
##    replicate    id neighbourhood room_type accommodates bathrooms bedrooms  beds
##        &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;         &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;
##  1         1  1276 Hastings-Sun… Entire h…            2 1 bath           1     1
##  2         1  3235 Hastings-Sun… Entire h…            2 1 bath           1     1
##  3         1  1301 Oakridge      Entire h…           12 2 baths          2    12
##  4         1   118 Grandview-Wo… Entire h…            4 1 bath           2     2
##  5         1  2550 Downtown Eas… Private …            2 1.5 shar…        1     1
##  6         1  1006 Grandview-Wo… Entire h…            5 1 bath           3     4
##  7         1  3632 Downtown Eas… Entire h…            6 2 baths          3     3
##  8         1  1923 West End      Entire h…            4 2 baths          2     2
##  9         1  3873 Dunbar South… Private …            5 1 bath           2     3
## 10         1  2349 Kerrisdale    Private …            2 1 shared…        1     1
## # ℹ 799,990 more rows
## # ℹ 1 more variable: price &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb502"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb502-1"><a href="inference.html#cb502-1" tabindex="-1"/><span class="fu">tail</span>(boot20000)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 9
## # Groups:   replicate [1]
##   replicate    id neighbourhood  room_type accommodates bathrooms bedrooms  beds
##       &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;
## 1     20000  1949 Kitsilano      Entire h…            3 1 bath           1     1
## 2     20000  1025 Kensington-Ce… Entire h…            3 1 bath           1     1
## 3     20000  3013 Kensington-Ce… Entire h…            4 1 bath           2     2
## 4     20000  2868 Downtown       Entire h…            2 1 bath           1     1
## 5     20000  3156 Downtown       Entire h…            6 2 baths          2     2
## 6     20000  1923 West End       Entire h…            4 2 baths          2     2
## # ℹ 1 more variable: price &lt;dbl&gt;</code></pre>
<p>Let’s take a look at the histograms of the first six replicates of our bootstrap samples.</p>
<div class="sourceCode" id="cb504"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb504-1"><a href="inference.html#cb504-1" tabindex="-1"/>six_bootstrap_samples <span class="ot">&lt;-</span> boot20000 <span class="sc">|&gt;</span></span>
<span id="cb504-2"><a href="inference.html#cb504-2" tabindex="-1"/>  <span class="fu">filter</span>(replicate <span class="sc">&lt;=</span> <span class="dv">6</span>)</span>
<span id="cb504-3"><a href="inference.html#cb504-3" tabindex="-1"/></span>
<span id="cb504-4"><a href="inference.html#cb504-4" tabindex="-1"/><span class="fu">ggplot</span>(six_bootstrap_samples, <span class="fu">aes</span>(price)) <span class="sc">+</span></span>
<span id="cb504-5"><a href="inference.html#cb504-5" tabindex="-1"/>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">"lightgrey"</span>) <span class="sc">+</span></span>
<span id="cb504-6"><a href="inference.html#cb504-6" tabindex="-1"/>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Price per night (dollars)"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb504-7"><a href="inference.html#cb504-7" tabindex="-1"/>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>replicate) <span class="sc">+</span></span>
<span id="cb504-8"><a href="inference.html#cb504-8" tabindex="-1"/>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:11-bootstrapping-six-bootstrap-samples"/>
<img src="../Images/bde1477438dd4ef7b988dfbad351bc06.png" alt="Histograms of the first six replicates of the bootstrap samples." width="672" data-original-src="https://datasciencebook.ca/_main_files/figure-html/11-bootstrapping-six-bootstrap-samples-1.png"/>
<p class="caption">
Figure 10.12: Histograms of the first six replicates of the bootstrap samples.
</p>
</div>
<p>We see in Figure <a href="inference.html#fig:11-bootstrapping-six-bootstrap-samples">10.12</a> how the
bootstrap samples differ. We can also calculate the sample mean for each of
these six replicates.</p>
<div class="sourceCode" id="cb505"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb505-1"><a href="inference.html#cb505-1" tabindex="-1"/>six_bootstrap_samples <span class="sc">|&gt;</span></span>
<span id="cb505-2"><a href="inference.html#cb505-2" tabindex="-1"/>  <span class="fu">group_by</span>(replicate) <span class="sc">|&gt;</span></span>
<span id="cb505-3"><a href="inference.html#cb505-3" tabindex="-1"/>  <span class="fu">summarize</span>(<span class="at">mean_price =</span> <span class="fu">mean</span>(price))</span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##   replicate mean_price
##       &lt;int&gt;      &lt;dbl&gt;
## 1         1     177.2 
## 2         2     131.45
## 3         3     179.10
## 4         4     171.35
## 5         5     191.32
## 6         6     170.05</code></pre>
<p>We can see that the bootstrap sample distributions and the sample means are
different. They are different because we are sampling <em>with replacement</em>. We
will now calculate point estimates for our 20,000 bootstrap samples and
generate a bootstrap distribution of our point estimates. The bootstrap
distribution (Figure <a href="inference.html#fig:11-bootstrapping5">10.13</a>) suggests how we might expect
our point estimate to behave if we took another sample.</p>
<div class="sourceCode" id="cb507"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb507-1"><a href="inference.html#cb507-1" tabindex="-1"/>boot20000_means <span class="ot">&lt;-</span> boot20000 <span class="sc">|&gt;</span></span>
<span id="cb507-2"><a href="inference.html#cb507-2" tabindex="-1"/>  <span class="fu">group_by</span>(replicate) <span class="sc">|&gt;</span></span>
<span id="cb507-3"><a href="inference.html#cb507-3" tabindex="-1"/>  <span class="fu">summarize</span>(<span class="at">mean_price =</span> <span class="fu">mean</span>(price))</span>
<span id="cb507-4"><a href="inference.html#cb507-4" tabindex="-1"/></span>
<span id="cb507-5"><a href="inference.html#cb507-5" tabindex="-1"/>boot20000_means</span></code></pre></div>
<pre><code>## # A tibble: 20,000 × 2
##    replicate mean_price
##        &lt;int&gt;      &lt;dbl&gt;
##  1         1     177.2 
##  2         2     131.45
##  3         3     179.10
##  4         4     171.35
##  5         5     191.32
##  6         6     170.05
##  7         7     178.83
##  8         8     154.78
##  9         9     163.85
## 10        10     209.28
## # ℹ 19,990 more rows</code></pre>
<div class="sourceCode" id="cb509"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb509-1"><a href="inference.html#cb509-1" tabindex="-1"/><span class="fu">tail</span>(boot20000_means)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##   replicate mean_price
##       &lt;int&gt;      &lt;dbl&gt;
## 1     19995     130.40
## 2     19996     189.18
## 3     19997     168.98
## 4     19998     168.23
## 5     19999     155.73
## 6     20000     136.95</code></pre>
<div class="sourceCode" id="cb511"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb511-1"><a href="inference.html#cb511-1" tabindex="-1"/>boot_est_dist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(boot20000_means, <span class="fu">aes</span>(<span class="at">x =</span> mean_price)) <span class="sc">+</span></span>
<span id="cb511-2"><a href="inference.html#cb511-2" tabindex="-1"/>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">"lightgrey"</span>) <span class="sc">+</span></span>
<span id="cb511-3"><a href="inference.html#cb511-3" tabindex="-1"/>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sample mean price per night (dollars)"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb511-4"><a href="inference.html#cb511-4" tabindex="-1"/>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb511-5"><a href="inference.html#cb511-5" tabindex="-1"/></span>
<span id="cb511-6"><a href="inference.html#cb511-6" tabindex="-1"/>boot_est_dist</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:11-bootstrapping5"/>
<img src="../Images/afa2d740f363d8701425b726f5a516da.png" alt="Distribution of the bootstrap sample means." width="432" data-original-src="https://datasciencebook.ca/_main_files/figure-html/11-bootstrapping5-1.png"/>
<p class="caption">
Figure 10.13: Distribution of the bootstrap sample means.
</p>
</div>
<p>Let’s compare the bootstrap distribution—which we construct by taking many samples from our original sample of size 40—with
the true sampling distribution—which corresponds to taking many samples from the population.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:11-bootstrapping6"/>
<img src="../Images/a781c8d138f28161630ead6cbb5304c0.png" alt="Comparison of the distribution of the bootstrap sample means and sampling distribution." width="672" data-original-src="https://datasciencebook.ca/_main_files/figure-html/11-bootstrapping6-1.png"/>
<p class="caption">
Figure 10.14: Comparison of the distribution of the bootstrap sample means and sampling distribution.
</p>
</div>
<p>There are two essential points that we can take away from Figure
<a href="inference.html#fig:11-bootstrapping6">10.14</a>. First, the shape and spread of the true sampling
distribution and the bootstrap distribution are similar; the bootstrap
distribution lets us get a sense of the point estimate’s variability. The
second important point is that the means of these two distributions are
different. The sampling distribution is centered at
$154.51, the population mean value. However, the bootstrap
distribution is centered at the original sample’s mean price per night,
$155.87. Because we are resampling from the
original sample repeatedly, we see that the bootstrap distribution is centered
at the original sample’s mean value (unlike the sampling distribution of the
sample mean, which is centered at the population parameter value).</p>
<p>Figure
<a href="inference.html#fig:11-bootstrapping7">10.15</a> summarizes the bootstrapping process.
The idea here is that we can use this distribution of bootstrap sample means to
approximate the sampling distribution of the sample means when we only have one
sample. Since the bootstrap distribution pretty well approximates the sampling
distribution spread, we can use the bootstrap spread to help us develop a
plausible range for our population parameter along with our estimate!</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:11-bootstrapping7"/>
<img src="../Images/2035ef72266f58ad60b70e1a2411a470.png" alt="Summary of bootstrapping process." width="672" data-original-src="https://datasciencebook.ca/_main_files/figure-html/11-bootstrapping7-1.png"/>
<p class="caption">
Figure 10.15: Summary of bootstrapping process.
</p>
</div>
</div>
<div id="using-the-bootstrap-to-calculate-a-plausible-range" class="section level3 hasAnchor" number="10.5.3">
<h3><span class="header-section-number">10.5.3</span> Using the bootstrap to calculate a plausible range<a href="inference.html#using-the-bootstrap-to-calculate-a-plausible-range" class="anchor-section" aria-label="Anchor link to header"/></h3>
<p>Now that we have constructed our bootstrap distribution, let’s use it to create
an approximate 95% percentile bootstrap confidence interval.
A <strong>confidence interval</strong> is a range of plausible values for the population parameter. We will
find the range of values covering the middle 95% of the bootstrap
distribution, giving us a 95% confidence interval. You may be wondering, what
does “95% confidence” mean? If we took 100 random samples and calculated 100
95% confidence intervals, then about 95% of the ranges would capture the
population parameter’s value. Note there’s nothing special about 95%. We
could have used other levels, such as 90% or 99%. There is a balance between
our level of confidence and precision. A higher confidence level corresponds to
a wider range of the interval, and a lower confidence level corresponds to a
narrower range. Therefore the level we choose is based on what chance we are
willing to take of being wrong based on the implications of being wrong for our
application. In general, we choose confidence levels to be comfortable with our
level of uncertainty but not so strict that the interval is unhelpful. For
instance, if our decision impacts human life and the implications of being
wrong are deadly, we may want to be very confident and choose a higher
confidence level.</p>
<p>To calculate a 95% percentile bootstrap confidence interval, we will do the following:</p>
<ol style="list-style-type: decimal">
<li>Arrange the observations in the bootstrap distribution in ascending order.</li>
<li>Find the value such that 2.5% of observations fall below it (the 2.5% percentile). Use that value as the lower bound of the interval.</li>
<li>Find the value such that 97.5% of observations fall below it (the 97.5% percentile). Use that value as the upper bound of the interval.</li>
</ol>
<div style="page-break-after: always;"/>
<p>To do this in R, we can use the <code>quantile()</code> function. Quantiles are expressed in proportions rather than
percentages, so the 2.5th and 97.5th percentiles would be the 0.025 and 0.975 quantiles, respectively.
</p>
<div class="sourceCode" id="cb512"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb512-1"><a href="inference.html#cb512-1" tabindex="-1"/>bounds <span class="ot">&lt;-</span> boot20000_means <span class="sc">|&gt;</span></span>
<span id="cb512-2"><a href="inference.html#cb512-2" tabindex="-1"/>  <span class="fu">select</span>(mean_price) <span class="sc">|&gt;</span></span>
<span id="cb512-3"><a href="inference.html#cb512-3" tabindex="-1"/>  <span class="fu">pull</span>() <span class="sc">|&gt;</span></span>
<span id="cb512-4"><a href="inference.html#cb512-4" tabindex="-1"/>  <span class="fu">quantile</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span>
<span id="cb512-5"><a href="inference.html#cb512-5" tabindex="-1"/></span>
<span id="cb512-6"><a href="inference.html#cb512-6" tabindex="-1"/>bounds</span></code></pre></div>
<pre><code>##  2.5% 97.5% 
##   119   204</code></pre>
<p>Our interval, $119.28 to $203.63, captures
the middle 95% of the sample mean prices in the bootstrap distribution. We can
visualize the interval on our distribution in Figure
<a href="inference.html#fig:11-bootstrapping9">10.16</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:11-bootstrapping9"/>
<img src="../Images/fbaae80dd3947cdba1a8345d4e157d84.png" alt="Distribution of the bootstrap sample means with percentile lower and upper bounds." width="624" data-original-src="https://datasciencebook.ca/_main_files/figure-html/11-bootstrapping9-1.png"/>
<p class="caption">
Figure 10.16: Distribution of the bootstrap sample means with percentile lower and upper bounds.
</p>
</div>
<p>To finish our estimation of the population parameter, we would report the point
estimate and our confidence interval’s lower and upper bounds. Here the sample
mean price per night of 40 Airbnb listings was
$155.80, and we are 95% “confident” that the true
population mean price per night for all Airbnb listings in Vancouver is between
$119.28 and $203.63.
Notice that our interval does indeed contain the true
population mean value, $154.51! However, in
practice, we would not know whether our interval captured the population
parameter or not because we usually only have a single sample, not the entire
population. This is the best we can do when we only have one sample!</p>
<p>This chapter is only the beginning of the journey into statistical inference.
We can extend the concepts learned here to do much more than report point
estimates and confidence intervals, such as testing for real differences
between populations, tests for associations between variables, and so much
more. We have just scratched the surface of statistical inference; however, the
material presented here will serve as the foundation for more advanced
statistical techniques you may learn about in the future!</p>
</div>
</div>
<div id="exercises-9" class="section level2 hasAnchor" number="10.6">
<h2><span class="header-section-number">10.6</span> Exercises<a href="inference.html#exercises-9" class="anchor-section" aria-label="Anchor link to header"/></h2>
<p>Practice exercises for the material covered in this chapter
can be found in the accompanying
<a href="https://worksheets.datasciencebook.ca">worksheets repository</a>
in the two “Statistical inference” rows.
You can launch an interactive version of each worksheet in your browser by clicking the “launch binder” button.
You can also preview a non-interactive version of each worksheet by clicking “view worksheet.”
If you instead decide to download the worksheets and run them on your own machine,
make sure to follow the instructions for computer setup
found in Chapter <a href="setup.html#setup">13</a>. This will ensure that the automated feedback
and guidance that the worksheets provide will function as intended.</p>
</div>
<div id="additional-resources-6" class="section level2 hasAnchor" number="10.7">
<h2><span class="header-section-number">10.7</span> Additional resources<a href="inference.html#additional-resources-6" class="anchor-section" aria-label="Anchor link to header"/></h2>
<ul>
<li>Chapters 7 to 10 of <em>Modern Dive</em> <span class="citation">(<a href="#ref-moderndive">Ismay and Kim 2020</a>)</span> provide a great
next step in learning about inference. In particular, Chapters 7 and 8 cover
sampling and bootstrapping using <code>tidyverse</code> and <code>infer</code> in a slightly more
in-depth manner than the present chapter. Chapters 9 and 10 take the next step
beyond the scope of this chapter and begin to provide some of the initial
mathematical underpinnings of inference and more advanced applications of the
concept of inference in testing hypotheses and performing regression. This
material offers a great starting point for getting more into the technical side
of statistics.</li>
<li>Chapters 4 to 7 of <em>OpenIntro Statistics</em> <span class="citation">(<a href="#ref-openintro">Diez, Çetinkaya-Rundel, and Barr 2019</a>)</span>
provide a good next step after <em>Modern Dive</em>. Although it is still certainly
an introductory text, things get a bit more mathematical here. Depending on
your background, you may actually want to start going through Chapters 1 to 3
first, where you will learn some fundamental concepts in probability theory.
Although it may seem like a diversion, probability theory is <em>the language of
statistics</em>; if you have a solid grasp of probability, more advanced statistics
will come naturally to you!</li>
</ul>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"/></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-insideairbnb" class="csl-entry">
Cox, Murray. n.d. <span>“Inside <span>Airbnb</span>.”</span> <a href="http://insideairbnb.com/">http://insideairbnb.com/</a>.
</div>
<div id="ref-openintro" class="csl-entry">
Diez, David, Mine Çetinkaya-Rundel, and Christopher Barr. 2019. <em>OpenIntro Statistics</em>. OpenIntro, Inc. <a href="https://openintro.org/book/os/">https://openintro.org/book/os/</a>.
</div>
<div id="ref-moderndive" class="csl-entry">
Ismay, Chester, and Albert Kim. 2020. <em>Statistical Inference via Data Science: A <span>M</span>odern<span>D</span>ive into <span>R</span> and the <span>T</span>idyverse</em>. Chapman; Hall/CRC Press. <a href="https://moderndive.com/">https://moderndive.com/</a>.
</div>
</div>
                
</body>
</html>