<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>3 Bivariate Statistics – Case Study United States Presidential Election</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1>3 Bivariate Statistics – Case Study United States Presidential Election</h1>
<blockquote>原文：<a href="https://bookdown.org/conradziller/introstatistics/bivariate-statistics-case-study-united-states-presidential-election.html">https://bookdown.org/conradziller/introstatistics/bivariate-statistics-case-study-united-states-presidential-election.html</a></blockquote><div id="bivariate-statistics-case-study-united-states-presidential-election" class="section level1" number="3">

<div id="introduction-1" class="section level2" number="3.1">
<h2>
<span class="header-section-number">3.1</span> Introduction<a class="anchor" aria-label="anchor" href="#introduction-1"/>
</h2>
<p>Studying the results of the 2020 US presidential election holds profound relevance in terms of understanding contemporary American politics, as well as research on electoral behavior. Analyzing the voting patterns unveils the interplay of demographics, ideology, and socio-economic factors shaping political preferences. Such insights not only inform electoral strategies but also deepen our comprehension of societal divisions and cleavages. The 2020 election also stands out through an effort to overturn the election result by Donald Trump and co-conspirators. This has caused turmoil and abet the January 6 United States Capitol attack (e.g., see <a href="https://www.britannica.com/event/January-6-U-S-Capitol-attack" target="„_blank“">https://www.britannica.com/event/January-6-U-S-Capitol-attack</a> and <a href="https://statesuniteddemocracy.org/resources/doj-charges-trump/" target="„_blank“">https://statesuniteddemocracy.org/resources/doj-charges-trump/</a>).</p>
<div class="inline-figure"><img src="../Images/4214df26bd25da76fee2ee7bb72854f6.png" id="id" class="class" style="width:50.0%;height:50.0%" data-original-src="https://bookdown.org/conradziller/introstatistics/picture/element5-digital-ls8Kc0P9hAA-unsplash.jpg"/></div>
<p>Source: <a href="https://unsplash.com/de/s/fotos/us-electionl" target="„_blank“">https://unsplash.com/de/s/fotos/us-election</a></p>
<p>Before the election, a team of researchers from the American National Election Study (ANES) conducted a large representative survey (based on a random sample of the US population) to study voting intentions. We will work with these data in this case study. We are particularly interested in which individuals are more likely to support Donald Trump compared to Joe Biden. In doing so, we will present data in the form of cross tabulations. We will also take a closer look at the topic of correlation analysis by investigating the relationship between average education and average Trum support across US states.</p>
<p><br/></p>
</div>
<div id="data-overview-and-descriptive-analyses" class="section level2" number="3.2">
<h2>
<span class="header-section-number">3.2</span> Data overview and descriptive analyses<a class="anchor" aria-label="anchor" href="#data-overview-and-descriptive-analyses"/>
</h2>
<p>The data are read from a CSV file (comma-separated values). By using the “head” command, the first six lines of the data are displayed.</p>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">data_us</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"data/data_election.csv"</span><span class="op">)</span></span>
<span><span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">data_us</span>, <span class="fl">10</span><span class="op">)</span>, booktabs <span class="op">=</span> <span class="cn">TRUE</span>,  caption <span class="op">=</span> <span class="st">'A table of the first 10 rows of the vote data.'</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">kable_paper</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">scroll_box</span><span class="op">(</span>width <span class="op">=</span> <span class="st">"100%"</span>, height <span class="op">=</span> <span class="st">"100%"</span><span class="op">)</span></span></code></pre></div>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:100%; overflow-x: scroll; width:100%; ">
<div class="inline-table"><table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-2">Table 3.1: </span><span id="tab:unnamed-chunk-2">Table 3.2: </span>A table of the first 10 rows of the vote data.
</caption>
<thead><tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
vote
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
trump
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
education
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
age
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
trump
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
46
</td>
</tr>
<tr>
<td style="text-align:left;">
other
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
37
</td>
</tr>
<tr>
<td style="text-align:left;">
biden
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
40
</td>
</tr>
<tr>
<td style="text-align:left;">
biden
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
41
</td>
</tr>
<tr>
<td style="text-align:left;">
trump
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
72
</td>
</tr>
<tr>
<td style="text-align:left;">
biden
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
71
</td>
</tr>
<tr>
<td style="text-align:left;">
trump
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
37
</td>
</tr>
<tr>
<td style="text-align:left;">
trump
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
45
</td>
</tr>
<tr>
<td style="text-align:left;">
refused / don’t know
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
43
</td>
</tr>
<tr>
<td style="text-align:left;">
biden
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
37
</td>
</tr>
</tbody>
</table></div>
</div>
<p><br/></p>
<p>We can see from this that the following variables are included in the dataset:</p>
<p><code>vote</code> = voting intention in the 2020 United States presidential election: “trump”, “biden”, “other”, “refused or don’t know”.</p>
<p><code>trump</code> = numerical recode of the <code>vote</code> variable. 1=“trump”, 0=“biden”, NA=“other / refused / don’t know”.</p>
<p><code>education</code> = respondent’s highest educational qualification: 1=no degree or high school, 2=some collage, 3=Associate or Bachelor’s degree, 4=Master’s or postgraduate degree, NA=not specified</p>
<p><code>age</code> = age of respondent in years.</p>
<p><br/></p>
<hr/>
<div class="alert alert-info">
<p><strong>Question:</strong> What is the scale of measurement (nominal, ordinal, metric) of each variable?</p>
</div>
<p><br/><br/>
Your answer:<br/></p>
<textarea name="textarea" cols="50" rows="5"/><p><br/></p>
<details><summary>
Solution:
</summary><br/><code>vote</code> and <code>trump</code> –&gt; nominal (i.e., information on if something is either the case or not, categories cannot be ranked and have no numerical meaning) <br/><code>education</code> –&gt; ordinal (i.e., categories (or variable values) can be ranked, information on whether a variable value is “higher”/“more” or “lower”/“less”) <br/><code>age</code> –&gt; metric (i.e., interval between ranked variable values can be compared; e.g., moving up 2 years from 20 to 22 is equivalent to moving up from 52 to 54) <br/></details><hr/>
<p><br/></p>
<div id="frequency-tables" class="section level3" number="3.2.1">
<h3>
<span class="header-section-number">3.2.1</span> Frequency tables<a class="anchor" aria-label="anchor" href="#frequency-tables"/>
</h3>
<p>The following table shows the observed frequencies of the values of the variable <code>vote</code>.</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">data_us</span><span class="op">)</span> <span class="co">#total number of cases</span></span></code></pre></div>
<pre><code>## [1] 7272    4</code></pre>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">data_us</span><span class="op">$</span><span class="va">vote</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
##                biden                other refused / don't know 
##                 3759                  274                  223 
##                trump 
##                 3016</code></pre>
<p><br/></p>
<p>We can see that 3,016 respondents chose Trump, whereas 3,759 opted for Biden. A difference of a couple of hundred responses. For a variable with only a few categories, looking at absolute numbers of observations might be informative. However, using relative frequencies in terms of proportions is typically more informative. Let’s get to it!</p>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">data_us</span><span class="op">$</span><span class="va">vote</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
##                biden                other refused / don't know 
##           0.51691419           0.03767877           0.03066557 
##                trump 
##           0.41474147</code></pre>
<p><br/></p>
<p>The relative difference between the group of Trump supporters and Biden supporters seems to be quite marginal in terms of percentage points. To be able to compare the figures from the survey data with the official vote result, we need to exclude the categories “refused (e.g., because respondent stated not going to vote) / don’t know”. To do so, we assign this category as “missing values,”</p>
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">data_us</span><span class="op">$</span><span class="va">vote</span><span class="op">[</span><span class="va">data_us</span><span class="op">$</span><span class="va">vote</span> <span class="op">==</span> <span class="st">"refused / don't know"</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="cn">NA</span> <span class="co"># Set "refused / don't know" to NA (i.e., missing), so that this category is no longer displayed in the table command</span></span>
<span/>
<span><span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">data_us</span><span class="op">$</span><span class="va">vote</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
##      biden      other      trump 
## 0.53326713 0.03887076 0.42786211</code></pre>
<p><br/></p>
<hr/>
<div class="alert alert-info">
<p><strong>Question:</strong> How well did the results from the survey predict the actual election outcome? Can we conclude from that whether or not the sample is representative?</p>
</div>
<p><br/><br/>
Your answer:<br/></p>
<textarea name="textarea" cols="50" rows="5"/><p><br/></p>
<details><summary>
Solution:
</summary><p><br/>
In the 2020 US presidential election, Biden won the popular vote against Trump by 51.3% to 46.9%. The survey results indicate that at the time the survey was conducted, 53.3% would have voted for Biden (compared to 42.8% for Trump). While the survey correctly predicted Biden as the winner, the result deviated from the actual election outcome by about 2 percentage points. Inferring from samples to the underlying population is always subject to some uncertainty. We can quantify margins of uncertainty, and we will do so in the case study on statistical inference. Beyond the role of statistical uncertainty, several further factors (e.g., political campaigning or situational circumstances on voting day) might have contributed to the outcome of the election result and possibly account for the difference between the survey results and the actual vote.</p>
The representativeness of a survey relates to its features, such as random sampling of respondents and no systematic non-response of those being interviewed. For the American Election Study, we have good reasons to assume that these features are given and the results are representative of the US population.<br/></details><hr/>
<p><br/></p>
<p>We will below also exclude the category “other candidates” that could have chosen in the survey and the election (together these candidates gathered less than 2% of the votes in the election). We will show later on how to recode variables. In the meantime, we can rely on the variable <code>trump</code> in which the categories “refused/don’t know” and “other” have already been set to NA (<em>not available</em> which is equal to <em>missing values</em> in terms of data analysis).</p>
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">data_us</span><span class="op">$</span><span class="va">trump</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
##         0         1 
## 0.5548339 0.4451661</code></pre>
</div>
<div id="a-note-on-missing-data-and-missing-values" class="section level3" number="3.2.2">
<h3>
<span class="header-section-number">3.2.2</span> A note on missing data and missing values<a class="anchor" aria-label="anchor" href="#a-note-on-missing-data-and-missing-values"/>
</h3>
<p>In survey data, missing data can occur through deliberate non-response of participants or other processes (e.g., a person has moved to a new address or is not eligible to vote). If the process that generated missing values is not known, this can potentially lead to biased results. A useful vignette on how to deal with missing data can be found here: <a href="https://cran.r-project.org/web/packages/finalfit/vignettes/missing.html" target="„_blank“"> https://cran.r-project.org/web/packages/finalfit/vignettes/missing.html</a></p>
<p>Regarding how to deal with missing values in data analyses, remember that in the variable <code>trump</code> the category “won’t vote” was recoded to NA, which means declaring to the program to not include these cases in the statistical analysis. Note that for some functions in R, it is necessary to explicitly exclude missing values (e.g., using the option “na.rm=TRUE”). Other functions do this automatically.</p>
<p>For example, the <em>table</em> command excludes missing values automatically, and if you want to display the frequency of missing values, you have to specify “<code>exclude=NULL</code>”. The <em>mean</em> command, however, does not exclude missing values automatically and therefore we have to specify the option “<code>na.rm=TRUE</code>” (i.e., “<em>NA remove</em> = TRUE”).</p>
<p><br/></p>
</div>
</div>
<div id="who-supports-trump---delving-into-bivariate-statistics" class="section level2" number="3.3">
<h2>
<span class="header-section-number">3.3</span> “Who supports Trump?” - Delving into bivariate statistics<a class="anchor" aria-label="anchor" href="#who-supports-trump---delving-into-bivariate-statistics"/>
</h2>
<p>In the following, we are interested in which groups of people were more likely to support Trump in the US presidential election. To do so, we focus on respondents’ education and age. Education is measured with a few categories. Hence, setting up a cross tabulation or cross tab (= a table involving two variables) is appropriate. In contrast, age is measured in years and thus comprises many more categories. This would make a cross tab involving age rather cumbersome. We could recode age into a few age categories and use them in a cross tab or we could compare age distributions across voting intentions. Below, we will explore both options.</p>
<p><br/></p>
<div id="education-and-trump-vote" class="section level3" number="3.3.1">
<h3>
<span class="header-section-number">3.3.1</span> Education and Trump vote<a class="anchor" aria-label="anchor" href="#education-and-trump-vote"/>
</h3>
<p>First, we are interested in whether or not people’s vote choice differs across education groups. If this is the case, we could state that education and voting intentions are statistically related or associated with each other. If not, both would be independent. Following conventions, the “variable to be explained” (a.k.a. outcome or dependent variable) is represented by the rows of the cross tab and the “explanatory variable” (a.k.a. causal factor or independent variable) by the columns. We calculate column percentages for the interpretation (i.e., the number of observations for each cell divided by the total number of observations for each column. Hence, adding all proportions per column adds up to 100%).
In our case, the causal order is quite clear. We have good reason to believe that (if anything) <code>education</code> determines voting intentions (<code>trump</code>) and <strong>not</strong> the other way around (i.e., voting intentions would cause higher or lower education). Note that in many other cases, the causal order is not as clear and we can freely choose which variable goes in the rows and which in the columns.</p>
<p><br/></p>
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">tab_xtab</span><span class="op">(</span>var.row <span class="op">=</span> <span class="va">data_us</span><span class="op">$</span><span class="va">trump</span>, var.col <span class="op">=</span> <span class="va">data_us</span><span class="op">$</span><span class="va">education</span>, show.col.prc <span class="op">=</span> <span class="cn">TRUE</span>, show.obs <span class="op">=</span> <span class="cn">TRUE</span>, show.summary <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="co">#show.col.prc = TRUE displays column percentages</span></span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
trump
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="4">
education
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
2
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
3
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
4
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
0
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">567</span><br/><span style="color:#339933;">45.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">687</span><br/><span style="color:#339933;">50.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1483</span><br/><span style="color:#339933;">55.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">974</span><br/><span style="color:#339933;">70.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">3711</span><br/><span style="color:#339933;">55.5 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
1
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">687</span><br/><span style="color:#339933;">54.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">685</span><br/><span style="color:#339933;">49.9 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1195</span><br/><span style="color:#339933;">44.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">407</span><br/><span style="color:#339933;">29.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">2974</span><br/><span style="color:#339933;">44.5 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1254</span><br/><span style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1372</span><br/><span style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">2678</span><br/><span style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1381</span><br/><span style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">6685</span><br/><span style="color:#339933;">100 %</span>
</td>
</tr>
</table></div>
<p><br/></p>
<p>For column percentages, the interpretation begins by picking two categories (adjacent or extreme) of the explanatory variable and then comparing a relevant category of the outcome.</p>
<blockquote>
<font size="-1"> <i><strong>Interpretation: Among those with low formal education (education=1), 54.8% of respondents support Trump, while in the highly educated group (education=4) only 29.5% support Trump. From this comparison, we can already conclude that education and Trump support are strongly related. The higher the education, the lower the preference for Trump, on average.</strong> </i> </font>
</blockquote>
<p><br/></p>
<p>Note that in the case of no systematic relationship between variables, the difference between two adjacent or opposite column values would be zero or close to zero (both values would closely correspond to the total proportion of 44.5%).</p>
<p>Important additions to the made interpretation would be (1) to quantify the strength of the empirical relationship (e.g., weak, medium, strong) and (2) to make a statement about how confident we can be that the empirical relationship found in the sample reflects the properties of the population the sample has been drawn from. There are procedures for both purposes, to which we will return to at the end of this case study.
Before that, however, let’s go back to cross tabs for a moment. Here, we see the same cross tab as above but with row percentages instead.</p>
<p><br/></p>
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">tab_xtab</span><span class="op">(</span>var.row <span class="op">=</span> <span class="va">data_us</span><span class="op">$</span><span class="va">trump</span>, var.col <span class="op">=</span> <span class="va">data_us</span><span class="op">$</span><span class="va">education</span>, show.row.prc <span class="op">=</span> <span class="cn">TRUE</span>, show.obs <span class="op">=</span> <span class="cn">TRUE</span>, show.summary <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="co">#show.row.prc = TRUE displays row percentages</span></span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
trump
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="4">
education
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
2
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
3
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
4
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
0
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">567</span><br/><span style="color:#333399;">15.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">687</span><br/><span style="color:#333399;">18.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1483</span><br/><span style="color:#333399;">40 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">974</span><br/><span style="color:#333399;">26.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">3711</span><br/><span style="color:#333399;">100 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
1
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">687</span><br/><span style="color:#333399;">23.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">685</span><br/><span style="color:#333399;">23 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1195</span><br/><span style="color:#333399;">40.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">407</span><br/><span style="color:#333399;">13.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">2974</span><br/><span style="color:#333399;">100 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1254</span><br/><span style="color:#333399;">18.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1372</span><br/><span style="color:#333399;">20.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">2678</span><br/><span style="color:#333399;">40.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1381</span><br/><span style="color:#333399;">20.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">6685</span><br/><span style="color:#333399;">100 %</span>
</td>
</tr>
</table></div>
<hr/>
<div class="alert alert-info">
<p><strong>Question:</strong> Which conclusions can be drawn from a cross tab with row percentages?</p>
</div>
<p><br/><br/>
Your answer:<br/></p>
<textarea name="textarea" cols="50" rows="5"/><p><br/></p>
<details><summary>
Solution:
</summary><p><br/>
Row percentages are the number of observations for each cell is divided by the total number of observations for each row (adding all proportions per row adds up to 100%). The interpretation would be similar to before, except that we now focus on comparing different categories of the row variable for one selected value of the column variable. Let’s select education = 1: Among those who do not support Trump (= Biden supporters), 15.3% have a low education profile, while among Trump supporters 23.1% have a low education profile. The difference of 7.8 percentage points suggests that Trump support and low education are systematically associated. Hence, the conclusion from the cross tab analysis with row percentages is equivalent to that one from column percentages (given that we adjust the interpretation scheme). Moreover, row percentages in this case also show the descriptive <em>distribution</em> of the education variable within each category of the vote variable. However, it is often not easy to compare the distributions at one glance.</p>
</details><hr/>
<p><br/></p>
<p>As a third possibility, below a cross tab with total percentages:</p>
<p><br/></p>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">tab_xtab</span><span class="op">(</span>var.row <span class="op">=</span> <span class="va">data_us</span><span class="op">$</span><span class="va">trump</span>, var.col <span class="op">=</span> <span class="va">data_us</span><span class="op">$</span><span class="va">education</span>, show.cell.prc <span class="op">=</span> <span class="cn">TRUE</span>, show.obs <span class="op">=</span> <span class="cn">TRUE</span>, show.summary <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="co">#show.cell.prc = TRUE displays cell or total percentages</span></span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
trump
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="4">
education
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
2
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
3
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
4
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
0
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">567</span><br/><span style="color:#993333;">8.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">687</span><br/><span style="color:#993333;">10.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1483</span><br/><span style="color:#993333;">22.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">974</span><br/><span style="color:#993333;">14.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">3711</span><br/><span style="color:#993333;">55.6 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
1
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">687</span><br/><span style="color:#993333;">10.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">685</span><br/><span style="color:#993333;">10.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1195</span><br/><span style="color:#993333;">17.9 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">407</span><br/><span style="color:#993333;">6.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">2974</span><br/><span style="color:#993333;">44.5 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1254</span><br/><span style="color:#993333;">18.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1372</span><br/><span style="color:#993333;">20.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">2678</span><br/><span style="color:#993333;">40.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1381</span><br/><span style="color:#993333;">20.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">6685</span><br/><span style="color:#993333;">100 %</span>
</td>
</tr>
</table></div>
<hr/>
<div class="alert alert-info">
<p><strong>Question:</strong> Which conclusions can be drawn from a cross tab with cell percentages?</p>
</div>
<p><br/><br/>
Your answer:<br/></p>
<textarea name="textarea" cols="50" rows="5"/><p><br/></p>
<details><summary>
Solution:
</summary><br/>
Total percentages are the number of observations for each cell divided by the total number of observations. This shows the relative frequency of each combination of values of the two variables. The goal is a descriptive understanding of the distribution of cases. (Note: This is rarely used in applied research.)
</details><hr/>
<p><br/></p>
</div>
<div id="age-and-trump-vote" class="section level3" number="3.3.2">
<h3>
<span class="header-section-number">3.3.2</span> Age and Trump vote<a class="anchor" aria-label="anchor" href="#age-and-trump-vote"/>
</h3>
<p>Due to the ‘age’ variable being recorded in years and thus having a large number of categories, a cross tab would be quite cumbersome and thus less informative. Therefore, we first create histograms displaying the distribution of the age variable for both categories of <code>trump</code> and then compare them with each other.</p>
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/lattice/man/histogram.html">histogram</a></span><span class="op">(</span> <span class="op">~</span> <span class="va">age</span> <span class="op">|</span> <span class="va">trump</span> ,</span>
<span>           breaks <span class="op">=</span> <span class="fl">10</span>, </span>
<span>           ylim<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">12</span><span class="op">)</span>,</span>
<span>           type <span class="op">=</span> <span class="st">"percent"</span>, </span>
<span>           main <span class="op">=</span> <span class="st">"Left: trump=0 (in support of Biden), Right: trump=1 (in support of Trump)"</span>,</span>
<span>           ylab <span class="op">=</span> <span class="st">"Percent of observations"</span>,</span>
<span>           xlab <span class="op">=</span> <span class="st">"Age in years"</span>,</span>
<span>           layout <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">1</span><span class="op">)</span>,</span>
<span>           scales <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>relation<span class="op">=</span><span class="st">"free"</span><span class="op">)</span>,</span>
<span>           col <span class="op">=</span> <span class="st">'grey'</span>,</span>
<span>           data <span class="op">=</span> <span class="va">data_us</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="../Images/857c066cee6269727bd9fb220f29bdb0.png" width="672" data-original-src="https://bookdown.org/conradziller/introstatistics/02-bivariate_trump_files/figure-html/unnamed-chunk-10-1.png"/></div>
<hr/>
<div class="alert alert-info">
<p><strong>Question:</strong> What can be inferred from the graphs?</p>
</div>
<p><br/><br/>
Your answer:<br/></p>
<textarea name="textarea" cols="50" rows="5"/><p><br/></p>
<details><summary>
Solution:
</summary><br/>
The age distribution of the respondents supporting Biden (left-hand) is a bit more even than the distribution of those supporting Trump (right-hand side). The latter is also more skewed to the left and its center is more on the right, which indicates that respondents who support Trump are older, on average, than those who support Biden.
</details><hr/>
<p><br/></p>
<p>In addition, here are the means and standard deviations of age by vote group.</p>
<p><em>Age mean, median, and standard deviation for Biden supporters:</em></p>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">data_us</span><span class="op">$</span><span class="va">age</span><span class="op">[</span><span class="va">data_us</span><span class="op">$</span><span class="va">trump</span> <span class="op">==</span> <span class="fl">0</span><span class="op">]</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 51.22253</code></pre>
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">data_us</span><span class="op">$</span><span class="va">age</span><span class="op">[</span><span class="va">data_us</span><span class="op">$</span><span class="va">trump</span> <span class="op">==</span> <span class="fl">0</span><span class="op">]</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 52</code></pre>
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">data_us</span><span class="op">$</span><span class="va">age</span><span class="op">[</span><span class="va">data_us</span><span class="op">$</span><span class="va">trump</span> <span class="op">==</span> <span class="fl">0</span><span class="op">]</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 17.22161</code></pre>
<p><br/></p>
<p><em>Age mean, median, and standard deviation for Trump supporters:</em></p>
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">data_us</span><span class="op">$</span><span class="va">age</span><span class="op">[</span><span class="va">data_us</span><span class="op">$</span><span class="va">trump</span> <span class="op">==</span> <span class="fl">1</span><span class="op">]</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 54.2871</code></pre>
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">data_us</span><span class="op">$</span><span class="va">age</span><span class="op">[</span><span class="va">data_us</span><span class="op">$</span><span class="va">trump</span> <span class="op">==</span> <span class="fl">1</span><span class="op">]</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 56</code></pre>
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">data_us</span><span class="op">$</span><span class="va">age</span><span class="op">[</span><span class="va">data_us</span><span class="op">$</span><span class="va">trump</span> <span class="op">==</span> <span class="fl">1</span><span class="op">]</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 16.51148</code></pre>
<p><br/></p>
<p>By comparing the mean and median values of both groups, we find that the Trump-supporting group is older than the group that supports Biden. The standard deviation (which can be thought of as the average deviation between the age of respondents and the mean) in the Biden group is slightly larger (17.2 years) than the standard deviation of the Trump group (16.5 years). This means that the age of respondents in the Biden group is slightly more dispersed than in the Trump group.</p>
<p><br/></p>
<p>In the next step, we recode the age variable into the categories “young” (1), “middle-aged” (2), and “old” (3). We then use a cross tab with column percentages.</p>
<div class="sourceCode" id="cb67"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">data_us</span> <span class="op">&lt;-</span> <span class="va">data_us</span> <span class="op">%&gt;%</span>  </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>age_cat <span class="op">=</span>  </span>
<span>           <span class="fu">case_when</span><span class="op">(</span><span class="va">age</span> <span class="op">&lt;=</span> <span class="fl">35</span> <span class="op">~</span> <span class="fl">1</span>,   </span>
<span>                     <span class="va">age</span> <span class="op">&gt;</span> <span class="fl">36</span> <span class="op">&amp;</span> <span class="va">age</span> <span class="op">&lt;=</span> <span class="fl">59</span> <span class="op">~</span> <span class="fl">2</span>,  </span>
<span>                     <span class="va">age</span> <span class="op">&gt;</span> <span class="fl">59</span> <span class="op">~</span> <span class="fl">3</span><span class="op">)</span><span class="op">)</span>  </span>
<span/>
<span/>
<span><span class="fu">tab_xtab</span><span class="op">(</span>var.row <span class="op">=</span> <span class="va">data_us</span><span class="op">$</span><span class="va">trump</span>, var.col <span class="op">=</span> <span class="va">data_us</span><span class="op">$</span><span class="va">age_cat</span>, show.col.prc <span class="op">=</span> <span class="cn">TRUE</span>, show.obs <span class="op">=</span> <span class="cn">TRUE</span>, show.summary <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
trump
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="3">
age_cat
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
2
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
3
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
0
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">838</span><br/><span style="color:#339933;">63.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1373</span><br/><span style="color:#339933;">55.7 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1375</span><br/><span style="color:#339933;">52.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">3586</span><br/><span style="color:#339933;">55.9 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
1
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">491</span><br/><span style="color:#339933;">36.9 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1092</span><br/><span style="color:#339933;">44.3 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1250</span><br/><span style="color:#339933;">47.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">2833</span><br/><span style="color:#339933;">44.1 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1329</span><br/><span style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">2465</span><br/><span style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">2625</span><br/><span style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">6419</span><br/><span style="color:#339933;">100 %</span>
</td>
</tr>
</table></div>
<hr/>
<div class="alert alert-info">
<p><strong>Question:</strong> Interpret the cross tab. What can be concluded? Why don’t we always go straight to categorizing metric variables and using the recoded variable in a cross tab?</p>
</div>
<p><br/><br/>
Your answer:<br/></p>
<textarea name="textarea" cols="50" rows="5"/><p><br/></p>
<details><summary>
Solution:
</summary><p><br/>
Looking at the category of young respondents (age_cat = 1), 36.9% prefer Trump as president, whereas among old respondents (age_cat = 3), 47.6% opt for Trump. This difference of 10.7 percentage points indicates a systematic (positive) empirical relationship between age and Trump support: Older respondents tend to prefer Trump more than younger voters.</p>
<p><br/></p>
The reason why it is not always recommended to categorize metric variables is that the process of categorization involves a loss of information. Usually, more information is better as it produces more detailed results. Note that there are exceptions to this such as striving for a simplified description of empirical relationships.
</details><hr/>
<p><br/></p>
<p>Here is a way to visualize a cross tab with stacked bar charts. The first figure corresponds to a cross tab with column percentages and the second figure relates to a cross tab with row percentages.</p>
<div class="sourceCode" id="cb68"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Age variable will be subdivided into the three dummy variables "young", "middle-aged", and "old"</span></span>
<span><span class="va">data_us</span> <span class="op">&lt;-</span> <span class="va">data_us</span> <span class="op">%&gt;%</span>  </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>age_cat_nom <span class="op">=</span>  </span>
<span>           <span class="fu">case_when</span><span class="op">(</span><span class="va">age</span> <span class="op">&lt;=</span> <span class="fl">35</span> <span class="op">~</span> <span class="st">"young"</span>,   </span>
<span>                     <span class="va">age</span> <span class="op">&gt;</span> <span class="fl">36</span> <span class="op">&amp;</span> <span class="va">age</span> <span class="op">&lt;=</span> <span class="fl">59</span> <span class="op">~</span> <span class="st">"middle-aged"</span>,  </span>
<span>                     <span class="va">age</span> <span class="op">&gt;</span> <span class="fl">59</span> <span class="op">~</span> <span class="st">"old"</span><span class="op">)</span><span class="op">)</span>  </span>
<span/>
<span><span class="va">data_us</span><span class="op">$</span><span class="va">age_cat_nom</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">data_us</span><span class="op">$</span><span class="va">age_cat_nom</span>, levels<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'young'</span>, <span class="st">'middle-aged'</span>, <span class="st">'old'</span><span class="op">)</span><span class="op">)</span></span>
<span> </span>
<span><span class="co"># Recoding of electoral participation </span></span>
<span><span class="va">data_us</span> <span class="op">&lt;-</span> <span class="va">data_us</span> <span class="op">%&gt;%</span>  </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>trump_nom <span class="op">=</span></span>
<span>           <span class="fu">case_when</span><span class="op">(</span><span class="va">trump</span> <span class="op">==</span> <span class="fl">0</span> <span class="op">~</span> <span class="st">"Favoring Biden"</span>,   </span>
<span>                     <span class="va">trump</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">~</span> <span class="st">"Favoring Trump"</span><span class="op">)</span><span class="op">)</span></span>
<span/>
<span><span class="va">data_us_counted</span> <span class="op">&lt;-</span> <span class="va">data_us</span>  <span class="op">%&gt;%</span>  <span class="fu">count</span><span class="op">(</span><span class="va">age_cat_nom</span>, <span class="va">trump_nom</span><span class="op">)</span></span>
<span><span class="va">data_us_counted</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">data_us_counted</span>, <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">data_us_counted</span><span class="op">$</span><span class="va">age_cat_nom</span><span class="op">)</span><span class="op">)</span> <span class="co"># removal of missing values</span></span>
<span><span class="va">data_us_counted</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">data_us_counted</span>, <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">data_us_counted</span><span class="op">$</span><span class="va">trump_nom</span><span class="op">)</span><span class="op">)</span> <span class="co"># removal of missing values</span></span>
<span/>
<span/>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">data_us_counted</span>, <span class="fu">aes</span><span class="op">(</span>fill<span class="op">=</span><span class="va">trump_nom</span>, y<span class="op">=</span><span class="va">n</span>, x<span class="op">=</span><span class="va">age_cat_nom</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_bar</span><span class="op">(</span>position<span class="op">=</span><span class="st">"fill"</span>, stat<span class="op">=</span><span class="st">"identity"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="va"><a href="https://scales.r-lib.org/reference/percent_format.html">percent</a></span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Age groups"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Shares"</span>,</span>
<span>       fill <span class="op">=</span> <span class="st">"Voting intention US presidential election"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="../Images/3a708062e933d62613551ae8fef2f89c.png" width="400px" height="300px" style="display: block; margin: auto;" data-original-src="https://bookdown.org/conradziller/introstatistics/02-bivariate_trump_files/figure-html/unnamed-chunk-14-1.png"/></div>
<div class="sourceCode" id="cb69"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">data_us_counted</span>, <span class="fu">aes</span><span class="op">(</span>fill<span class="op">=</span><span class="va">age_cat_nom</span>, y<span class="op">=</span><span class="va">n</span>, x<span class="op">=</span><span class="va">trump_nom</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_bar</span><span class="op">(</span>position<span class="op">=</span><span class="st">"fill"</span>, stat<span class="op">=</span><span class="st">"identity"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="va"><a href="https://scales.r-lib.org/reference/percent_format.html">percent</a></span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">coord_flip</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Voting intention US presidential election"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Shares"</span>,</span>
<span>       fill <span class="op">=</span> <span class="st">"Age groups"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="../Images/252d77af5e2b86b359df6cdc8a279436.png" width="400px" height="300px" style="display: block; margin: auto;" data-original-src="https://bookdown.org/conradziller/introstatistics/02-bivariate_trump_files/figure-html/unnamed-chunk-15-1.png"/></div>
<p><br/></p>
</div>
</div>
<div id="scatter-plot-and-correlation" class="section level2" number="3.4">
<h2>
<span class="header-section-number">3.4</span> Scatter plot and correlation<a class="anchor" aria-label="anchor" href="#scatter-plot-and-correlation"/>
</h2>
<p>Scatter plots and correlation are suitable for showing relationships between two variables. In the following, we use the average approval of Trump across US states in % (<code>perc_trump</code>) as the variable to be explained (a.k.a. the outcome or dependent variable). State-specific variations in voting patterns are illustrated in the following map. As an explanatory variable, we use the proportion of people in the state who have a high level of education (Master’s or postgraduate) in % (<code>perc_higheducation</code>). Both variables originate from individual-level data of the ANES study and have been aggregated to the state level (i.e., the means per region were stored in a new dataset).</p>
<div class="float" id="id">
<img src="../Images/df8ff4c600f60647e1fd13df8a34e904.png" class="class" style="width:50.0%;height:50.0%" alt="Regional US presidential election results" data-original-src="https://bookdown.org/conradziller/introstatistics/picture/map_states.png"/><div class="figcaption">Regional US presidential election results</div>
</div>
<p>Source: <a href="https://www.governing.com/assessments/what-painted-us-so-indelibly-red-and-blue" target="„_blank“">https://www.governing.com/assessments/what-painted-us-so-indelibly-red-and-blue</a></p>
<p>Next, the data are read and the first six rows are displayed:</p>
<div class="sourceCode" id="cb70"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">data_states</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"data/data_states.csv"</span><span class="op">)</span></span>
<span><span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">data_states</span>, <span class="fl">10</span><span class="op">)</span>, booktabs <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>  caption <span class="op">=</span> <span class="st">'A table of the first 10 rows of the regional vote data.'</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">kable_paper</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">scroll_box</span><span class="op">(</span>width <span class="op">=</span> <span class="st">"100%"</span>, height <span class="op">=</span> <span class="st">"100%"</span><span class="op">)</span></span></code></pre></div>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:100%; overflow-x: scroll; width:100%; ">
<div class="inline-table"><table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-16">Table 3.3: </span><span id="tab:unnamed-chunk-16">Table 3.4: </span>A table of the first 10 rows of the regional vote data.
</caption>
<thead><tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
state
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
perc_trump
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
perc_higheducation
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
<ol start="46" style="list-style-type: decimal"><li>South Dakota
</li></ol>
</td>
<td style="text-align:right;">
0.7333334
</td>
<td style="text-align:right;">
0.0588235
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="31" style="list-style-type: decimal"><li>Nebraska
</li></ol>
</td>
<td style="text-align:right;">
0.5416667
</td>
<td style="text-align:right;">
0.0816327
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="45" style="list-style-type: decimal"><li>South Carolina
</li></ol>
</td>
<td style="text-align:right;">
0.5000000
</td>
<td style="text-align:right;">
0.0840336
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="38" style="list-style-type: decimal"><li>North Dakota
</li></ol>
</td>
<td style="text-align:right;">
0.7619048
</td>
<td style="text-align:right;">
0.0869565
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="30" style="list-style-type: decimal"><li>Montana
</li></ol>
</td>
<td style="text-align:right;">
0.5238095
</td>
<td style="text-align:right;">
0.0869565
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="5" style="list-style-type: decimal"><li>Arkansas
</li></ol>
</td>
<td style="text-align:right;">
0.7142857
</td>
<td style="text-align:right;">
0.1132075
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="22" style="list-style-type: decimal"><li>Louisiana
</li></ol>
</td>
<td style="text-align:right;">
0.6022728
</td>
<td style="text-align:right;">
0.1170213
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="55" style="list-style-type: decimal"><li>Wisconsin
</li></ol>
</td>
<td style="text-align:right;">
0.5031056
</td>
<td style="text-align:right;">
0.1180124
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="2" style="list-style-type: decimal"><li>Alaska
</li></ol>
</td>
<td style="text-align:right;">
0.7500000
</td>
<td style="text-align:right;">
0.1250000
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="49" style="list-style-type: decimal"><li>Utah
</li></ol>
</td>
<td style="text-align:right;">
0.5526316
</td>
<td style="text-align:right;">
0.1250000
</td>
</tr>
</tbody>
</table></div>
</div>










<p>The variable <code>state</code> identifies the region.</p>
<p><br/></p>
<div id="scatter-plot" class="section level3" number="3.4.1">
<h3>
<span class="header-section-number">3.4.1</span> Scatter plot<a class="anchor" aria-label="anchor" href="#scatter-plot"/>
</h3>
<p>To get a first impression of the empirical relationship between both variables, we use a scatter plot. Each point represents one of the 50 US states and Washington D.C. Note that it is a convention that the dependent variable is shown on the y-axis, whereas the independent variable is shown on the x-axis.</p>
<div class="sourceCode" id="cb71"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">sc1</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">data_states</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">perc_higheducation</span>, y <span class="op">=</span> <span class="va">perc_trump</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">xlab</span><span class="op">(</span><span class="st">"Share of highly-educated persons in %"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">ylab</span><span class="op">(</span><span class="st">"Support of Trump in %"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="va"><a href="https://scales.r-lib.org/reference/percent_format.html">percent</a></span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="va"><a href="https://scales.r-lib.org/reference/percent_format.html">percent</a></span><span class="op">)</span></span>
<span/>
<span><span class="va">sc1</span></span></code></pre></div>
<div class="inline-figure"><img src="../Images/74133aa4cb55fe6fb934060c4fbadb92.png" width="672" data-original-src="https://bookdown.org/conradziller/introstatistics/02-bivariate_trump_files/figure-html/unnamed-chunk-17-1.png"/></div>
<hr/>
<div class="alert alert-info">
<p><strong>Question:</strong> What can be inferred from the figure?</p>
</div>
<p><br/><br/>
Your answer:<br/></p>
<textarea name="textarea" cols="50" rows="5"/><p><br/></p>
<details><summary>
Solution:
</summary><br/>
The pattern indicates a <em>negative</em> relationship between the two variables. If the proportion of highly educated people in a region increases (moving to the right on the x-axis), we see that this is related to <em>lower</em> support for Trump (lower scores on the y-axis).
</details><hr/>
<p><br/></p>
</div>
<div id="correlation" class="section level3" number="3.4.2">
<h3>
<span class="header-section-number">3.4.2</span> Correlation<a class="anchor" aria-label="anchor" href="#correlation"/>
</h3>
<p>In the next step, we will take a graphical approach to how a correlation is determined. For this, we plot a vertical and a horizontal line that represents the mean of the variables through the cloud of observations represented by the black dots. We see that the dots are mainly in the upper-left quadrant (= low proportion of high education AND high Trump approval) and the lower-right quadrant (= high proportion of high education AND low Trumo approval). This indicates that higher average education tends to be associated with <em>lower</em> average Trump approval. In other words: The correlation is negative.</p>
<div class="sourceCode" id="cb72"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">#Obtaining means for each variable</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">data_states</span><span class="op">$</span><span class="va">perc_trump</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 0.470922</code></pre>
<div class="sourceCode" id="cb74"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">data_states</span><span class="op">$</span><span class="va">perc_higheducation</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 0.1927645</code></pre>
<div class="sourceCode" id="cb76"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">#Scatter plot using percentages as scale units</span></span>
<span><span class="va">sc2</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">data_states</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">perc_higheducation</span>, y <span class="op">=</span> <span class="va">perc_trump</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">xlab</span><span class="op">(</span><span class="st">"Share of highly-educated persons in %"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">ylab</span><span class="op">(</span><span class="st">"Support of Trump in %"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="va"><a href="https://scales.r-lib.org/reference/percent_format.html">percent</a></span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="va"><a href="https://scales.r-lib.org/reference/percent_format.html">percent</a></span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_hline</span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">0.470922</span>, linetype<span class="op">=</span><span class="st">"dashed"</span>, color <span class="op">=</span> <span class="st">"red"</span>, size<span class="op">=</span><span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_vline</span><span class="op">(</span>xintercept<span class="op">=</span><span class="fl">0.1927645</span>, linetype<span class="op">=</span><span class="st">"dashed"</span>, color <span class="op">=</span> <span class="st">"red"</span>, size<span class="op">=</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">sc2</span></span></code></pre></div>
<div class="inline-figure"><img src="../Images/f144be86d1419e69cadcc105fd9d9f43.png" width="672" data-original-src="https://bookdown.org/conradziller/introstatistics/02-bivariate_trump_files/figure-html/unnamed-chunk-18-1.png"/></div>
<p>To quantify the relationship, we can calculate the covariance and subsequently the correlation (= standardized covariance fitted into the value range of -1 to +1). The widely used Pearson’s correlation coefficient is given as:</p>
<p><span class="math inline">\(r=\frac{Covariance(x,y)}{SD(x)*SD(y)}\)</span></p>
<p><span class="math inline">\(r=\frac{\sum_{i=1}^{n}(x_i-\bar{x})(y_i-\bar{y})}{\sqrt{\sum_{i=1}^{n}(x_i-\bar{x})^2}\sqrt{\sum_{i=1}^{n}(y_i-\bar{y})^2}}\)</span></p>
<p>The numerator <span class="math inline">\({\sum_{i=1}^{n}(x_i-\bar{x})(y_i-\bar{y})}\)</span> is particularly important. It represents the <strong>covariance</strong>, which is an <em>unstandardized</em> measure of association between x and y because its value heavily depends on the scales x and y are measured. At the same time, it serves to determine the direction of the empirical association. To do so, the classification of observations into above/below the mean quadrants is useful again. Observations that are above both means (i.e., upper right corner) have a positive sign and contribute as a product to a “positive” covariance or correlation. The same is true for observations in the lower left quadrant because here both differences have a negative sign, which again contributes as a product to a positive covariance (and thus correlation). In contrast, observations in the upper left and lower right quadrants contribute to a negative covariance (and thus correlation). If observations are evenly distributed across all quadrants, positive and negative products cancel each other out, which would lead to a zero covariance (and thus correlation). The step from covariance to correlation is that the covariance is <em>standardized</em> by the standard deviation of x and y which removes the scale units covariance is measured on and transforms the measure to range between -1 and +1.</p>
<p>Here is an overview of possible scenarios in the correlation coefficient:</p>
<div class="float" id="id">
<img src="../Images/def5619515dfea46c9ae284c25c25731.png" class="class" style="width:100.0%;height:100.0%" alt="Different correlations" data-original-src="https://bookdown.org/conradziller/introstatistics/picture/korr2.png"/><div class="figcaption">Different correlations</div>
</div>
<p>Source: <a href="https://en.wikipedia.org/wiki/Correlation#/media/File:Correlation_examples2.svg" class="uri">https://en.wikipedia.org/wiki/Correlation#/media/File:Correlation_examples2.svg</a></p>
<p>Scatter plots showing correlations (from left to right) of -1, -0.8, -0.4, 0, 0.4, 0.8 and 1.</p>
<p><br/></p>
<p>In the next step, the correlation between the share of highly educated people and the share of Trump supporters is calculated and a line representing their relationship is plotted. The line essentially depicts the bivariate association in the form of a regression slope, which always runs in the direction of the correlation. However, its interpretation differs from correlation.</p>
<div class="sourceCode" id="cb77"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">sc3</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">data_states</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">perc_higheducation</span>, y <span class="op">=</span> <span class="va">perc_trump</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">xlab</span><span class="op">(</span><span class="st">"Share of highly-educated persons in %"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">ylab</span><span class="op">(</span><span class="st">"Support of Trump in %"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="va"><a href="https://scales.r-lib.org/reference/percent_format.html">percent</a></span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="va"><a href="https://scales.r-lib.org/reference/percent_format.html">percent</a></span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_smooth</span><span class="op">(</span>method <span class="op">=</span> <span class="va">lm</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">sc3</span></span></code></pre></div>
<div class="inline-figure"><img src="../Images/d49a117c960c96522d1a4ec77b2e09f0.png" width="80%" height="80%" style="display: block; margin: auto;" data-original-src="https://bookdown.org/conradziller/introstatistics/02-bivariate_trump_files/figure-html/unnamed-chunk-19-1.png"/></div>
<div class="sourceCode" id="cb78"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">vars</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"perc_higheducation"</span>, <span class="st">"perc_trump"</span><span class="op">)</span></span>
<span><span class="va">cor.vars</span> <span class="op">&lt;-</span> <span class="va">data_states</span><span class="op">[</span><span class="va">vars</span><span class="op">]</span></span>
<span><span class="fu">rcorr</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span><span class="op">(</span><span class="va">cor.vars</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##                    perc_higheducation perc_trump
## perc_higheducation               1.00      -0.69
## perc_trump                      -0.69       1.00
## 
## n= 51 
## 
## 
## P
##                    perc_higheducation perc_trump
## perc_higheducation                     0        
## perc_trump          0</code></pre>
<p>In the case of correlation and regression coefficients, the interpretation always begins with mentioning x (or the <strong>independent</strong> variable) which exerts an effect on y (or the <strong>dependent</strong> variable).</p>
<ul>
<li><p><strong>Correlation coefficient:</strong> “If x increases, then y increases / decreases (depending on the sign of the correlation coefficient), on average. The magnitude of the correlation coefficient <em>r</em> indicates a <em>weak/moderate/strong</em> empirical association.” (Rule of thumb: +/- 0.1 <em>weak</em>, +/- 0.3 <em>moderate</em>, +/- 0.5 or higher <em>strong</em> association)</p></li>
<li><p><strong>Regression coefficient:</strong> “If x increases by one unit, then y increases / decreases (depending on the sign of the regression coefficient) by <em>coefficient</em> units, on average.” The specific coefficient estimate that is referred to, is given in the regression output. To what extent the empirical relationship is strong, moderate, or weak can be determined by a standardization of the regression coefficients. Note that the details of regression analysis and its interpretation are covered in the case study on regression analysis.</p></li>
<li><p>Correlation is a standardized form of covariance, which comes with the advantage of being intuitively interpretable (-1 to +1) without any reference to the underlying scale the two variables are measured. However, the price to pay is that it conceals the <em>magnitude</em> by which y changes if x changes by one unit (rather it represents how dense observations cluster together in forming a linear relationship). Bivariate regression quantifies the expected increase in y if x increases by 1. We thus need to standardize (or “correct”) the covariance between x and y for the scale on which x is measured. This is achieved by dividing the covariance by the variance of x: <span class="math inline">\(b=\frac{Covariance(x,y)}{Var(x)}\)</span></p></li>
</ul>
<p><br/></p>
<blockquote>
<font size="-1"> <i><strong>Interpretation of the correlation coefficient from the example: The correlation between the proportion of people with high education and Trump support is negative. If the share of people with high education increases, then Trump support decreases, on average. The correlation coefficient of -0.69 indicates a strong empirical relationship between both variables.</strong> </i> </font>
</blockquote>
<p><br/><br/></p>
</div>
</div>
<div id="chi-square-and-cramérs-v" class="section level2" number="3.5">
<h2>
<span class="header-section-number">3.5</span> Chi-square and Cramér’s V<a class="anchor" aria-label="anchor" href="#chi-square-and-cram%C3%A9rs-v"/>
</h2>
<p>Now we return to cross tabs and how to make a statement about whether there is a correlation between the displayed variables and if so, how strong it is. To do so, we once again revisit the individual-level survey data and display the cross tab between <code>education</code> and <code>trump</code>.</p>
<div class="sourceCode" id="cb80"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">tab_xtab</span><span class="op">(</span>var.row <span class="op">=</span> <span class="va">data_us</span><span class="op">$</span><span class="va">trump</span>, var.col <span class="op">=</span> <span class="va">data_us</span><span class="op">$</span><span class="va">education</span>, show.col.prc <span class="op">=</span> <span class="cn">TRUE</span>, show.obs <span class="op">=</span> <span class="cn">TRUE</span>, show.summary <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="co">#setting show.summary = TRUE displays summary statistics at the bottom of the table</span></span></code></pre></div>
<div class="inline-table"><table style="border-collapse:collapse; border:none;" class="table table-sm">
<tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
trump
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="4">
education
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
2
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
3
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
4
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
0
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">567</span><br/><span style="color:#339933;">45.2 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">687</span><br/><span style="color:#339933;">50.1 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1483</span><br/><span style="color:#339933;">55.4 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">974</span><br/><span style="color:#339933;">70.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">3711</span><br/><span style="color:#339933;">55.5 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
1
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">687</span><br/><span style="color:#339933;">54.8 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">685</span><br/><span style="color:#339933;">49.9 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1195</span><br/><span style="color:#339933;">44.6 %</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">407</span><br/><span style="color:#339933;">29.5 %</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">2974</span><br/><span style="color:#339933;">44.5 %</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1254</span><br/><span style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1372</span><br/><span style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">2678</span><br/><span style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1381</span><br/><span style="color:#339933;">100 %</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">6685</span><br/><span style="color:#339933;">100 %</span>
</td>
</tr>
<td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="6">
χ<sup>2</sup>=196.388 · df=3 · Cramer’s V=0.171 · p=0.000
</td>

</table></div>
<p>It has already become quite clear that low-educated people were more likely to support Trump compared to high-educated people (who were more in favor of Biden). To quantify the empirical association, we can calculate Cramér’s V. This measure quantifies empirical relationships if a nominal variable is involved (here: <code>trump</code>). It is based on a chi-square test for independence. The chi-square value indicates how strongly the real observations deviate from a theoretical distribution, wherein all observations are equally distributed (relative to marginal distribution) across the cells of the cross tab. The more the measured observations deviate from the theoretical distribution, the higher the chi-square value and subsequently Cramér’s V gets, which is normalized for the table size and ranges between 0 (= no association) and 1 (= exceedingly strong association).</p>
<p>The formula for the chi-square test for cross tabs is the following: <span class="math inline">\(\chi^2= \sum{\frac{(O-E)^2}{E}}\)</span></p>
<p><span class="math inline">\(O\)</span> refers to the observed frequencies and <span class="math inline">\(E\)</span> to the expected ones. The expected frequencies are obtained by multiplying the marginal frequencies (“total”) for each cell, divided by the total number of cases (<span class="math inline">\(E = \frac{R\times C}{n}\)</span>). For the first cell in the table above, this would be (1254*3711)/6685=696.12. Thus, 696 observations would be theoretically expected in the first cell and 567 were observed. Quite different. This is done (usually through statistical software) for each cell and summed up according to the formula.</p>
<p>Cramér’s V is a measure based on chi-square and adjusted for different-sized cross tabs. It is given by the formula: <span class="math inline">\(V=\sqrt{\frac{\chi^2}{n\times (m-1)}}\)</span>, where <span class="math inline">\(n\)</span> is the number of observations and <span class="math inline">\(M\)</span> is the number of categories (or variable values) of the variable with the fewer categories (here <code>trump</code> with 2).</p>
<p>Regarding interpretation, the following guidelines apply:</p>
<ul>
<li>Cramér’s V ranges from 0 to 1, with no negative values possible</li>
<li>Hence, Cramér’s V provides no information on whether the association is positive or negative, we have to figure this out from the table (e.g., by calculating percentage differences between column values –&gt; see above)</li>
<li>Rules of thumb regarding the size of the relationship:
<ul>
<li>In a small table (e.g., 2x2): between 0.1 and 0.3 –&gt; weak, more than 0.3 and less than 0.5 –&gt; moderate, more than 0.5 –&gt; strong association</li>
<li>In a large table (e.g., 5x5): between 0.05 and 0.15 –&gt; weak, more than 0.15 and less than 0.25 –&gt; moderate, more than 0.25 –&gt; strong association</li>
</ul>
</li>
</ul>
<p>In R, chi-square and Cramér’s V can be calculated with the following commands:</p>
<div class="sourceCode" id="cb81"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span><span class="op">(</span><span class="va">data_us</span><span class="op">$</span><span class="va">trump</span>, <span class="va">data_us</span><span class="op">$</span><span class="va">education</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
##  Pearson's Chi-squared test
## 
## data:  data_us$trump and data_us$education
## X-squared = 196.39, df = 3, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb83"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">cramerV_tabelle</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">data_us</span><span class="op">$</span><span class="va">trump</span>, <span class="va">data_us</span><span class="op">$</span><span class="va">education</span><span class="op">)</span></span>
<span><span class="fu">cramerV</span><span class="op">(</span><span class="va">cramerV_tabelle</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Cramer V 
##   0.1714</code></pre>
<hr/>
<div class="alert alert-info">
<p><strong>Question:</strong> How can Cramér’s V be interpreted in this case?</p>
</div>
<p><br/><br/>
Your answer:<br/></p>
<textarea name="textarea" cols="50" rows="5"/><p><br/></p>
<details><summary>
Solution:
</summary><p><br/></p>
<blockquote>
<font size="-1"> <i><strong>Interpretation: There is an association between the variables <code>education</code> and <code>trump</code>. Given the rule of thumb for small tables, the association of 0.17 is weak. In our case, we know from the interpretation above that the association is negative (the higher the education, the lower the approval of Trump, on average).</strong> </i> </font>
</blockquote>
</details><hr/>
<p><br/></p>
<hr/>
<div class="alert alert-info">
<p><strong>Question:</strong> Why didn’t we calculate the Pearson’s correlation coefficient instead?</p>
</div>
<p><br/><br/>
Your answer:<br/></p>
<textarea name="textarea" cols="50" rows="5"/><p><br/></p>
<details><summary>
Solution:
</summary><br/>
Pearson’s correlation coefficient requires (quasi-)metric variables with several categories. For ordinal variables, we have tools such as Kendall’s Tau or Spearman’s correlation coefficient (see here for more on different correlation types: <a href="https://ademos.people.uic.edu/Chapter22.html" target="„_blank“">https://ademos.people.uic.edu/Chapter22.html</a>). If nominal variables are involved, we use coefficients such as Cramér’s V.
</details><hr/>
<p><br/><br/></p>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="univariate-statistics-case-study-socio-demographic-reporting.html"><span class="header-section-number">2</span> Univariate Statistics – Case Study Socio-Demographic Reporting</a></div>
<div class="next"><a href="statistical-inference---case-study-satisfaction-with-government.html"><span class="header-section-number">4</span> Statistical Inference - Case Study Satisfaction with Government</a></div>
</div>    
</body>
</html>