<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>2 Univariate Statistics – Case Study Socio-Demographic Reporting</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1>2 Univariate Statistics – Case Study Socio-Demographic Reporting</h1>
<blockquote>原文：<a href="https://bookdown.org/conradziller/introstatistics/univariate-statistics-case-study-socio-demographic-reporting.html">https://bookdown.org/conradziller/introstatistics/univariate-statistics-case-study-socio-demographic-reporting.html</a></blockquote><div id="univariate-statistics-case-study-socio-demographic-reporting" class="section level1" number="2">

<div id="introduction" class="section level2" number="2.1">
<h2>
<span class="header-section-number">2.1</span> Introduction<a class="anchor" aria-label="anchor" href="#introduction"/>
</h2>
<p>The 2020 socio-demographic report on the German state North-Rhine Westphalia continues the state’s social reporting since its beginning in 1992. These reports aim to provide the public with information on the social and demographic conditions and dynamics of North Rhine-Westphalia (NRW).</p>
<p>Social indicators refer to demographic conditions and developments (e.g., population figures, the proportion of people with a migration background), the economy (e.g., unemployment rates, GDP), health, education, housing, public finances, and social inequality.</p>
<p>The report and underlying data we are dealing with in this case study can be accessed online via <a href="https://www.sozialberichte.nrw.de" target="„_blank“">https://www.sozialberichte.nrw.de</a>.</p>
<div class="float" id="id">
<img src="../Images/94ed8dc6172bfcc8f9239a2818b4c276.png" class="class" style="width:50.0%;height:50.0%" alt="Cover Sozialbericht" data-original-src="https://bookdown.org/conradziller/introstatistics/picture/cover.png"/><div class="figcaption">Cover Sozialbericht</div>
</div>
<p><br/></p>
<p>Analyses based on data from the socio-demographic report are politically relevant. Insights from data analyses may provide politicians and public officials with information on social problems that need to be addressed by political measures. It is thus important that interpretations derived from data analyses are accurate. In the following case study, we take a closer look at the data and use methods from univariate statistics. Please note that the analyses and interpretations below are meant to illustrate data analysis techniques and do not reflect any policy advice.</p>
<p>We will use the following indicators or <em>variables</em> (source <a href="https://www.inkar.de" target="„_blank“">https://www.inkar.de</a>):</p>
<ul>
<li>Population density</li>
<li>Proportion of foreigners</li>
<li>Proportion of unemployed</li>
<li>Crime rate</li>
<li>Average age</li>
</ul>
<p><br/></p>
</div>
<div id="preparing-the-data" class="section level2" number="2.2">
<h2>
<span class="header-section-number">2.2</span> Preparing the data<a class="anchor" aria-label="anchor" href="#preparing-the-data"/>
</h2>
<p>Before we can analyze the data, they must be read in the data analysis program. R uses a lot of so-called “packages” (i.e., software add-ons that facilitate or simplify specific parts of data analysis). For example, the package “readxl” allows us to read data that is stored in an Excel format. As another example, the package “ggplot2” allows us to create print-ready figures. Packages often have a specific syntax to which we refer along the way.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://readxl.tidyverse.org">readxl</a></span><span class="op">)</span> <span class="co"># This command loads the package "readxl". In the markdown document, all required packages are installed in the background using the command "install.packages('packagename')". In the downloadable script files, the installation and activation of the packages is automated. </span></span>
<span/>
<span><span class="va">data_nrw</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readxl.tidyverse.org/reference/read_excel.html">read_excel</a></span><span class="op">(</span><span class="st">"data/inkar_nrw.xls"</span><span class="op">)</span> <span class="co"># Reads data from Excel format; the directory where the data is to be found can be changed (e.g., "C:/user/documents/folderxyz/inkar_nrw.xls")</span></span></code></pre></div>
<p>After reading the file “inkar_nrw.xlsx”, it is stored as an object in R. We can now work with the data. As a first step, we print the first ten rows of the data frame:</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">kable</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">data_nrw</span>, <span class="fl">10</span><span class="op">)</span>, format <span class="op">=</span> <span class="st">"html"</span>, caption <span class="op">=</span> <span class="st">"Selected social indicators NRW"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">kable_paper</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="co">#Font scheme of the table</span></span>
<span>  <span class="fu">scroll_box</span><span class="op">(</span>width <span class="op">=</span> <span class="st">"100%"</span>, height <span class="op">=</span> <span class="st">"100%"</span><span class="op">)</span> <span class="co">#Scrollable box</span></span></code></pre></div>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:100%; overflow-x: scroll; width:100%; ">
<div class="inline-table"><table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-3">Table 2.1: </span>Selected social indicators NRW
</caption>
<thead><tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
kkziff
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
area
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
aggregat
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
nonnational
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
population
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
flaeche
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
unemp
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
avage
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
crimerate
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
KN
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
05111
</td>
<td style="text-align:left;">
Düsseldorf, Stadt
</td>
<td style="text-align:left;">
kreisfreie Stadt
</td>
<td style="text-align:right;">
20.69
</td>
<td style="text-align:right;">
620523
</td>
<td style="text-align:right;">
217
</td>
<td style="text-align:right;">
7.77
</td>
<td style="text-align:right;">
42.65
</td>
<td style="text-align:right;">
9998.762
</td>
<td style="text-align:right;">
5111000
</td>
</tr>
<tr>
<td style="text-align:left;">
05112
</td>
<td style="text-align:left;">
Duisburg, Stadt
</td>
<td style="text-align:left;">
kreisfreie Stadt
</td>
<td style="text-align:right;">
21.86
</td>
<td style="text-align:right;">
495885
</td>
<td style="text-align:right;">
233
</td>
<td style="text-align:right;">
12.10
</td>
<td style="text-align:right;">
43.05
</td>
<td style="text-align:right;">
8640.908
</td>
<td style="text-align:right;">
5112000
</td>
</tr>
<tr>
<td style="text-align:left;">
05113
</td>
<td style="text-align:left;">
Essen, Stadt
</td>
<td style="text-align:left;">
kreisfreie Stadt
</td>
<td style="text-align:right;">
16.87
</td>
<td style="text-align:right;">
582415
</td>
<td style="text-align:right;">
210
</td>
<td style="text-align:right;">
11.04
</td>
<td style="text-align:right;">
43.68
</td>
<td style="text-align:right;">
7472.201
</td>
<td style="text-align:right;">
5113000
</td>
</tr>
<tr>
<td style="text-align:left;">
05114
</td>
<td style="text-align:left;">
Krefeld, Stadt
</td>
<td style="text-align:left;">
kreisfreie Stadt
</td>
<td style="text-align:right;">
17.54
</td>
<td style="text-align:right;">
226844
</td>
<td style="text-align:right;">
138
</td>
<td style="text-align:right;">
11.11
</td>
<td style="text-align:right;">
44.28
</td>
<td style="text-align:right;">
8866.532
</td>
<td style="text-align:right;">
5114000
</td>
</tr>
<tr>
<td style="text-align:left;">
05116
</td>
<td style="text-align:left;">
Mönchengladbach, Stadt
</td>
<td style="text-align:left;">
kreisfreie Stadt
</td>
<td style="text-align:right;">
17.09
</td>
<td style="text-align:right;">
259665
</td>
<td style="text-align:right;">
170
</td>
<td style="text-align:right;">
10.02
</td>
<td style="text-align:right;">
43.74
</td>
<td style="text-align:right;">
8256.396
</td>
<td style="text-align:right;">
5116000
</td>
</tr>
<tr>
<td style="text-align:left;">
05117
</td>
<td style="text-align:left;">
Mülheim an der Ruhr, Stadt
</td>
<td style="text-align:left;">
kreisfreie Stadt
</td>
<td style="text-align:right;">
16.12
</td>
<td style="text-align:right;">
170921
</td>
<td style="text-align:right;">
91
</td>
<td style="text-align:right;">
8.31
</td>
<td style="text-align:right;">
45.23
</td>
<td style="text-align:right;">
5285.058
</td>
<td style="text-align:right;">
5117000
</td>
</tr>
<tr>
<td style="text-align:left;">
05119
</td>
<td style="text-align:left;">
Oberhausen, Stadt
</td>
<td style="text-align:left;">
kreisfreie Stadt
</td>
<td style="text-align:right;">
15.83
</td>
<td style="text-align:right;">
209566
</td>
<td style="text-align:right;">
77
</td>
<td style="text-align:right;">
10.76
</td>
<td style="text-align:right;">
44.52
</td>
<td style="text-align:right;">
7378.869
</td>
<td style="text-align:right;">
5119000
</td>
</tr>
<tr>
<td style="text-align:left;">
05120
</td>
<td style="text-align:left;">
Remscheid, Stadt
</td>
<td style="text-align:left;">
kreisfreie Stadt
</td>
<td style="text-align:right;">
19.15
</td>
<td style="text-align:right;">
111516
</td>
<td style="text-align:right;">
75
</td>
<td style="text-align:right;">
7.97
</td>
<td style="text-align:right;">
44.37
</td>
<td style="text-align:right;">
5635.991
</td>
<td style="text-align:right;">
5120000
</td>
</tr>
<tr>
<td style="text-align:left;">
05122
</td>
<td style="text-align:left;">
Solingen, Klingenstadt
</td>
<td style="text-align:left;">
kreisfreie Stadt
</td>
<td style="text-align:right;">
17.13
</td>
<td style="text-align:right;">
159193
</td>
<td style="text-align:right;">
90
</td>
<td style="text-align:right;">
8.15
</td>
<td style="text-align:right;">
44.11
</td>
<td style="text-align:right;">
5933.624
</td>
<td style="text-align:right;">
5122000
</td>
</tr>
<tr>
<td style="text-align:left;">
05124
</td>
<td style="text-align:left;">
Wuppertal, Stadt
</td>
<td style="text-align:left;">
kreisfreie Stadt
</td>
<td style="text-align:right;">
20.81
</td>
<td style="text-align:right;">
355004
</td>
<td style="text-align:right;">
168
</td>
<td style="text-align:right;">
9.95
</td>
<td style="text-align:right;">
43.11
</td>
<td style="text-align:right;">
8059.420
</td>
<td style="text-align:right;">
5124000
</td>
</tr>
</tbody>
</table></div>
</div>
<p><br/><br/> The data contains the following variables for all 53 districts and large cities in North-Rhine Westphalia (reference year is 2020):</p>
<p><code>kkziff</code> = identifier code for the county (<em>Landkreis</em>) or city (<em>kreisfreie Stadt</em>)</p>
<p><code>area</code> = County / city name</p>
<p><code>nonnationall</code> = Proportion of foreign-born residents in %</p>
<p><code>population</code> = Number of inhabitants</p>
<p><code>flaeche</code> = Land area in square kilometers</p>
<p><code>unemp</code> = Unemployment rate in %</p>
<p><code>avage</code> = Average age of the population</p>
<p><code>crimerate</code> = Crime rate in cases per 100,000 inhabitants</p>
<p><code>KN</code> = Alternative id code that we need for the map below</p>
<p><br/></p>
</div>
<div id="representation-of-spatial-patterns-using-maps" class="section level2" number="2.3">
<h2>
<span class="header-section-number">2.3</span> Representation of spatial patterns using maps<a class="anchor" aria-label="anchor" href="#representation-of-spatial-patterns-using-maps"/>
</h2>
<p>One option to represent spatially structured data is in the form of a map.</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Read a so-called shape file for NRW which contains the polygones (e.g., district boundaries) necessary to build maps and merging with structural data</span></span>
<span><span class="va">nrw_shp</span> <span class="op">&lt;-</span> <span class="fu">st_read</span><span class="op">(</span><span class="st">"data/dvg2krs_nw.shp"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Reading layer `dvg2krs_nw' from data source 
##   `C:\Users\ziller\OneDrive - Universitaet Duisburg-Essen\Statistik Bookdown\IntroStats\IS\data\dvg2krs_nw.shp' 
##   using driver `ESRI Shapefile'
## Simple feature collection with 53 features and 8 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: 280375 ymin: 5577680 xmax: 531791.2 ymax: 5820212
## Projected CRS: ETRS89 / UTM zone 32N</code></pre>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">nrw_shp</span><span class="op">$</span><span class="va">KN</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="va">nrw_shp</span><span class="op">$</span><span class="va">KN</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">nrw_shp</span> <span class="op">&lt;-</span> <span class="va">nrw_shp</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">right_join</span><span class="op">(</span><span class="va">data_nrw</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"KN"</span><span class="op">)</span><span class="op">)</span></span>
<span/>
<span><span class="co"># Building the map using the "ggplot2" package</span></span>
<span/>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">nrw_shp</span>, <span class="fu">aes</span><span class="op">(</span>fill <span class="op">=</span> <span class="va">unemp</span><span class="op">)</span>, color <span class="op">=</span> <span class="st">'gray'</span>, size <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span> <span class="op">+</span> </span>
<span><span class="fu">ggtitle</span><span class="op">(</span><span class="st">"North-Rhine Westphalia, Germany"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">guides</span><span class="op">(</span>fill<span class="op">=</span><span class="fu">guide_colorbar</span><span class="op">(</span>title<span class="op">=</span><span class="st">"Unemployment in %"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">scale_fill_gradientn</span><span class="op">(</span>colours<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/rev.html">rev</a></span><span class="op">(</span><span class="fu">magma</span><span class="op">(</span><span class="fl">3</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                       na.value <span class="op">=</span> <span class="st">"grey100"</span>, </span>
<span>                      <span class="op">)</span> </span></code></pre></div>
<div class="inline-figure"><img src="../Images/3e8407e259dabffce793d31c3884598c.png" width="672" data-original-src="https://bookdown.org/conradziller/introstatistics/01-univariate_files/figure-html/unnamed-chunk-4-1.png"/></div>
<p><br/></p>
<hr/>
<div class="alert alert-info">
<p><strong>Question:</strong> What information is conveyed by the map? What information remains implicit?</p>
</div>
<p><br/><br/>
Your answer:<br/></p>
<p><br/></p>

Solution:

<p><br/></p>
<ul>
<li><p>Maps give a good first impression of the spatial distribution of data.</p></li>
<li><p>However, insights depend on further (implicit) information (“What are the specifics of the high-unemployment cities in the middle of the map? Which areas are rural, which are urban?”).</p></li>
<li><p>Difficult to make general statements about maps and to compare maps (especially if the breaks that underly the colorization differ).</p></li>
</ul>
<br/><hr/>
<p><br/></p>
</div>
<div id="distributions-first-insights-into-the-data-structure" class="section level2" number="2.4">
<h2>
<span class="header-section-number">2.4</span> Distributions: First insights into the data structure<a class="anchor" aria-label="anchor" href="#distributions-first-insights-into-the-data-structure"/>
</h2>
<p>To get an impression about the distribution of the data, histograms can be used (e.g., What are minimum or maximum values? Do observed values are clusterd around the center of the distrubtion or are they widely spread?). Histograms show the frequency of observations across the range of values of a variable. It does not matter how the single observations (i.e., districts in our case) appear in the data set. The histogram ranks observations depending on the values they have on a specific variable. The height of the displayed bars is proportional to the frequency of observations that have corresponding variable values. The width of the bars (also known as bins) represents an interval of values and can be customized (i.e., a few wide bars comprise more observations than many narrow ones).</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://lattice.r-forge.r-project.org/">lattice</a></span><span class="op">)</span></span>
<span/>
<span><span class="va">data_nrw</span><span class="op">$</span><span class="va">popdens</span> <span class="op">&lt;-</span> <span class="va">data_nrw</span><span class="op">$</span><span class="va">population</span><span class="op">/</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">flaeche</span> <span class="co"># This generates the variable for the population density</span></span>
<span/>
<span><span class="fu"><a href="https://rdrr.io/pkg/lattice/man/histogram.html">histogram</a></span><span class="op">(</span> <span class="op">~</span> <span class="va">popdens</span> <span class="op">+</span> <span class="va">unemp</span> <span class="op">+</span> <span class="va">avage</span> <span class="op">+</span> <span class="va">crimerate</span>,</span>
<span>           breaks <span class="op">=</span> <span class="fl">10</span>, </span>
<span>           type <span class="op">=</span> <span class="st">"percent"</span>, </span>
<span>           xlab <span class="op">=</span> <span class="st">""</span>,</span>
<span>           ylab <span class="op">=</span> <span class="st">"Percent of observations"</span>, </span>
<span>           layout <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">1</span><span class="op">)</span>,</span>
<span>           scales <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>relation<span class="op">=</span><span class="st">"free"</span><span class="op">)</span>,</span>
<span>           col <span class="op">=</span> <span class="st">'grey'</span>,</span>
<span>           data <span class="op">=</span> <span class="va">data_nrw</span><span class="op">)</span></span></code></pre></div>
<p><img src="../Images/0d609b47a0edeb9a05625752e8e7446c.png" width="672" data-original-src="https://bookdown.org/conradziller/introstatistics/01-univariate_files/figure-html/unnamed-chunk-5-1.png"/><img src="../Images/a076dcbcd37b73dc7b7e46b0f0b5452b.png" width="672" data-original-src="https://bookdown.org/conradziller/introstatistics/01-univariate_files/figure-html/unnamed-chunk-5-2.png"/></p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">## Alternative approach with the "hist"-function</span></span>
<span><span class="co">#hist(data_nrw$unemp)</span></span>
<span><span class="co">#hist(data_nrw$avage)</span></span>
<span><span class="co">#hist(data_nrw$crimerate)</span></span></code></pre></div>
<p><br/></p>
<hr/>
<div class="alert alert-info">
<p><strong>Question:</strong> Which characteristics of the data can be identified with histograms? Which aspects remain hidden?</p>
</div>
<p><br/><br/>
Your answer:<br/></p>
<p><br/></p>

Solution:

<p><br/>
What can be seen: The distribution of the data, including the center(s) where most of the observations are located, patterns of skewness, and outliers.</p>
<p>What remains hidden: The specific estimates of the summary statistics (e.g., mean, variance).</p>
<br/><hr/>
<p><br/></p>
</div>
<div id="mean" class="section level2" number="2.5">
<h2>
<span class="header-section-number">2.5</span> Mean<a class="anchor" aria-label="anchor" href="#mean"/>
</h2>
<p>The mean of a variable is also referred to as a measure of central tendency. It thus represents a good first impression of what is a typical (or expectable) value of a measured characteristic (i.e., a variable). Comparing the mean and the variable value of a specific observation provides information about whether the observation is close to or far from the mean. Besides the arithmetic mean, other measures exist (e.g., the geometric mean), but we do not consider them here.</p>
<p><strong>For the calculation of the mean, all observed values for a variable are added and the sum is then divided by the total number of observations (n).</strong></p>
<p><span class="math inline">\(\bar x = \frac{1}{n}\sum_{i=1}^n x_i\)</span> or <span class="math inline">\(\mu = \frac{1}{N}\sum_{i=1}^N x_i\)</span></p>
<p><span class="math inline">\(\bar x\)</span> and n refer to given data we are working with (e.g., from a <em>sample</em>), <span class="math inline">\(\mu\)</span> and N refer to the <em>population</em> we want to make statistical statements about. (Note: This distinction becomes relevant in statistical testing, where we use a random sample to draw inferences about an underlying larger population.)</p>
<p><br/></p>
<p>Let’s take a look at the means and other information on the variables in the data set:</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">)</span></span></code></pre></div>
<pre><code>##     kkziff              area             aggregat          nonnational   
##  Length:53          Length:53          Length:53          Min.   : 6.05  
##  Class :character   Class :character   Class :character   1st Qu.: 9.82  
##  Mode  :character   Mode  :character   Mode  :character   Median :12.19  
##                                                           Mean   :13.45  
##                                                           3rd Qu.:16.87  
##                                                           Max.   :21.86  
##    population         flaeche           unemp            avage      
##  Min.   : 111516   Min.   :  51.0   Min.   : 3.110   Min.   :40.97  
##  1st Qu.: 226844   1st Qu.: 170.0   1st Qu.: 5.740   1st Qu.:43.33  
##  Median : 308335   Median : 543.0   Median : 6.950   Median :44.15  
##  Mean   : 338218   Mean   : 643.6   Mean   : 7.432   Mean   :44.01  
##  3rd Qu.: 408662   3rd Qu.:1112.0   3rd Qu.: 8.850   3rd Qu.:44.62  
##  Max.   :1083498   Max.   :1960.0   Max.   :14.870   Max.   :45.81  
##    crimerate           KN             popdens      
##  Min.   : 3718   Min.   :5111000   Min.   : 116.3  
##  1st Qu.: 4906   1st Qu.:5166000   1st Qu.: 278.5  
##  Median : 5636   Median :5512000   Median : 784.7  
##  Mean   : 6244   Mean   :5506094   Mean   :1072.0  
##  3rd Qu.: 7568   3rd Qu.:5770000   3rd Qu.:1768.8  
##  Max.   :10500   Max.   :5978000   Max.   :3077.3</code></pre>
<p><br/></p>
<hr/>
<div class="alert alert-info">
<p><strong>Question:</strong> Interpret two means of your choice. Why is no mean displayed for the variable <code>area</code>?</p>
</div>
<p><br/><br/>
Your answer:<br/></p>
<p><br/></p>

Solution:

<p><br/>
The average unemployment rate across the observed districts is 7.4 percent. The mean of the population variable is 338,218, which means that about 338,218 people live in a region, on average.</p>
<p>Means can only be calculated for metric or quasi-metric (typically an ordinal variable with five or more categories) variables. <code>area</code> is a nominal variable.</p>
<br/><hr/>
<p><br/></p>
<p>The displayed tables contain more information than means:</p>
<ul>
<li>The <strong>median</strong> is another measure of centrality (besides the mean and the mode, i.e., the variable value that occurs the most often for a given set of observations):
<ul>
<li>The median is the midpoint of a frequency distribution of observed variable values (i.e., it divides ordered observed data into two equal parts).</li>
<li>Often preferred over the mean for skewed data because the median is not sensitive to outliers (i.e., extreme values).</li>
</ul>
</li>
<li>Measures of dispersion, such as the <strong>range</strong> (i.e., maximum value – minimum value) and the <strong>standard deviation</strong>, both providing information about how the data is distributed.</li>
<li>Measures of position, such as <strong>quartiles</strong> and the interquartile range, which are often graphically depicted using boxplots.</li>
</ul>
<p><br/></p>
</div>
<div id="measures-of-dispersion-variance-and-standard-deviation" class="section level2" number="2.6">
<h2>
<span class="header-section-number">2.6</span> Measures of dispersion: Variance and standard deviation<a class="anchor" aria-label="anchor" href="#measures-of-dispersion-variance-and-standard-deviation"/>
</h2>
<p>Imagine for a moment that we not only have the socio-demographic report of NRW available but also a report from another German state. Comparing county characteristics, such as crime rates, across the two states might result in finding that both have the exact same mean. However, the crime rate in State 1 is much more extremely distributed, with particularly high and low values for some counties. In State 2, in contrast, the crime rate is much more evenly distributed around the mean. Determining the degree of dispersion (or scatteredness) of data is an important piece of information that is useful for several further statistical analyses It might also yield practical relevance, as different patterns of dispersion of crime may lead to different policy measures for combating crime.
Let us start with calculating the variance.</p>
<p><strong>The variance is the sum of squared deviations</strong>.</p>
<p><span class="math inline">\(\sigma^2 = \frac{\sum_{i=1}^n (x_i-\mu)^2}{N}\)</span> (Notation for the population)
<span class="math inline">\(s^2 = \frac{\sum_{i=1}^n (x_i-\bar x)^2}{n-1}\)</span> (Notation for the sample; If we apply statistical inference and use a random sample, we need to apply a correction in the denominator “n-1” – referred to as Bessel’s correction)</p>
<p><strong>The standard deviation re-transforms the value back to the scale on which the variable is measured, it is therefore easier to interpret and more commonly used</strong>.</p>
<p><span class="math inline">\(s = \sqrt{\frac{\sum_{i=1}^n (x_i-\bar x)^2}{n-1}}\)</span></p>
<p>Here you find a graphical representation of the dispersion of the variables <code>unemp</code> and <code>crimerate</code>. Note that the deviations between observations on the x-axis are purely random to increase the readability of the plot (otherwise, all observations would be lined up like a vertical pearl necklace). The red line is the mean value.</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">s_unemp</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">data_nrw</span>, <span class="fu">aes</span><span class="op">(</span>y<span class="op">=</span><span class="va">unemp</span>, x<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/reorder.factor.html">reorder</a></span><span class="op">(</span><span class="va">area</span>, <span class="va">area</span><span class="op">)</span>, color<span class="op">=</span><span class="va">area</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_jitter</span><span class="op">(</span>height <span class="op">=</span> <span class="fl">0</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"Unemployment rate 2020 in %"</span><span class="op">)</span></span>
<span><span class="va">s_unemp</span> <span class="op">+</span> <span class="fu">geom_hline</span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">7.432</span>, linetype<span class="op">=</span><span class="st">"solid"</span>, color <span class="op">=</span> <span class="st">"red"</span>, size<span class="op">=</span><span class="fl">0.1</span><span class="op">)</span> <span class="op">+</span> <span class="fu">theme</span><span class="op">(</span>legend.position<span class="op">=</span><span class="st">"bottom"</span><span class="op">)</span> <span class="op">+</span> <span class="fu">theme</span><span class="op">(</span>legend.text <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span>size<span class="op">=</span><span class="fl">5</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu">theme</span><span class="op">(</span>axis.title.x<span class="op">=</span><span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,        axis.text.x<span class="op">=</span><span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,        axis.ticks.x<span class="op">=</span><span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="../Images/34533e1c6a4b7e5afda02c1a679b778c.png" width="672" data-original-src="https://bookdown.org/conradziller/introstatistics/01-univariate_files/figure-html/unnamed-chunk-7-1.png"/></div>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">s_crime</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">data_nrw</span>, <span class="fu">aes</span><span class="op">(</span>y<span class="op">=</span><span class="va">crimerate</span>, x<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/reorder.factor.html">reorder</a></span><span class="op">(</span><span class="va">area</span>, <span class="va">area</span><span class="op">)</span>, color<span class="op">=</span><span class="va">area</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_jitter</span><span class="op">(</span>height <span class="op">=</span> <span class="fl">0</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"Crime rate 2020"</span><span class="op">)</span></span>
<span/>
<span><span class="va">s_crime</span> <span class="op">+</span> <span class="fu">geom_hline</span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">6244</span>, linetype<span class="op">=</span><span class="st">"solid"</span>, color <span class="op">=</span> <span class="st">"red"</span>, size<span class="op">=</span><span class="fl">0.1</span><span class="op">)</span>  <span class="op">+</span> <span class="fu">theme</span><span class="op">(</span>legend.position<span class="op">=</span><span class="st">"bottom"</span><span class="op">)</span> <span class="op">+</span> <span class="fu">theme</span><span class="op">(</span>legend.text <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span>size<span class="op">=</span><span class="fl">5</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu">theme</span><span class="op">(</span>axis.title.x<span class="op">=</span><span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,        axis.text.x<span class="op">=</span><span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,        axis.ticks.x<span class="op">=</span><span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="../Images/3b051a03bee8c053a4ff845313f85bda.png" width="672" data-original-src="https://bookdown.org/conradziller/introstatistics/01-univariate_files/figure-html/unnamed-chunk-7-2.png"/></div>
<p><br/></p>
<hr/>
<div class="alert alert-info">
<p><strong>Question:</strong> Can you spot which district has the highest unemployment rate? Which county has the lowest crime rate? Can we infer from the graphs which of the two variables is more dispersed?</p>
</div>
<p><br/><br/>
Your answer:<br/></p>
<p><br/></p>

Solution:

<p><br/>
It is quite hard to match the color of the dots with the ones of the legend. Gelsenkirchen has the highest unemployment rate at 14.9%. The district with the lowest crime rate is Lippe.</p>
<p>Because of the different scaling of the variables, it is not possible to infer from this plot which variable is more dispersed. To do so, we would need to calculate the so-called coefficient of variation (see below).</p>
<br/><hr/>
<p><br/></p>
<p>Standard deviation, range, and coefficient of variation calculated with R (unemployment):</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">unemp</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 2.477591</code></pre>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">range</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">unemp</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">unemp</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">range</span> </span></code></pre></div>
<pre><code>## [1] 11.76</code></pre>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">varcoef</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">unemp</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">unemp</span><span class="op">)</span> <span class="op">*</span> <span class="fl">100</span> <span class="co">#how much percent of the mean is the standard deviation?</span></span>
<span><span class="va">varcoef</span></span></code></pre></div>
<pre><code>## [1] 33.33815</code></pre>
<p>Standard deviation, min/max, and coefficient of variation calculated with R (crime rate):</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">crimerate</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 1775.389</code></pre>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">range</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">crimerate</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">crimerate</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">range</span> </span></code></pre></div>
<pre><code>## [1] 6782.056</code></pre>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">varcoef</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">crimerate</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">crimerate</span><span class="op">)</span> <span class="op">*</span> <span class="fl">100</span></span>
<span><span class="va">varcoef</span></span></code></pre></div>
<pre><code>## [1] 28.43261</code></pre>
<p><br/></p>
<p>To compare the dispersion of variables measured on different scales, we cannot use the variance or standard deviation (as they are measured on the units of the scale) but employ the coefficient of variation (i.e., standard deviation over the mean times 100). Here, higher values imply a higher dispersion of the data.</p>
<blockquote>
<font size="-1"> <i><strong>Interpretation: The variable unemployment is more heterogeneously dispersed (varcoef = 33.3) than the variable crime rate (varcoef = 28.4).</strong> </i> </font>
</blockquote>
<p><br/></p>
</div>
<div id="position-measures-boxplots-and-interquartile-range" class="section level2" number="2.7">
<h2>
<span class="header-section-number">2.7</span> Position measures: Boxplots and interquartile range<a class="anchor" aria-label="anchor" href="#position-measures-boxplots-and-interquartile-range"/>
</h2>
<p>Quartiles divide the ordered data into four parts (Q1 to Q4, where Q4 is the maximum of the observed values), and the median is represented by Q2. Hence, 25% of the observations are below or at Q1, 75% above. Q3-Q1 = interquartile range (IQR), which reflects the range in which the middle 50% of the observations are located.</p>
<div class="float" id="id">
<img src="../Images/7182b21d77cf421b22eb68ef86f85830.png" class="class" style="width:50.0%;height:50.0%" alt="Quartiles" data-original-src="https://bookdown.org/conradziller/introstatistics/picture/quartiles.PNG"/><div class="figcaption">Quartiles</div>
</div>
<p>Quartiles and IQR for unemployment rate:</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">unemp</span><span class="op">)</span></span></code></pre></div>
<pre><code>##    0%   25%   50%   75%  100% 
##  3.11  5.74  6.95  8.85 14.87</code></pre>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">unemp.score.quart</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">unemp</span>, names <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">unemp.score.quart</span><span class="op">[</span><span class="fl">4</span><span class="op">]</span> <span class="op">-</span> <span class="va">unemp.score.quart</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span></span></code></pre></div>
<pre><code>## [1] 3.11</code></pre>
<p>Quartiles and IQR for crime rate:</p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">crimerate</span><span class="op">)</span></span></code></pre></div>
<pre><code>##        0%       25%       50%       75%      100% 
##  3718.411  4906.122  5635.991  7568.376 10500.467</code></pre>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">crimerate.score.quart</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">crimerate</span>, names <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">crimerate.score.quart</span><span class="op">[</span><span class="fl">4</span><span class="op">]</span> <span class="op">-</span> <span class="va">crimerate.score.quart</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span></span></code></pre></div>
<pre><code>## [1] 2662.254</code></pre>
<p>Boxplots graphically represent the key figures Q1, Q2, Q3. The lower and upper ends of the whiskers are usually the minimum and maximum observed values. To mark observations that are far away from the median (so-called outliers), the maximal width of a whisker is restricted to Q1 - 1.5 x IQR (for the lower whisker) and Q3 + 1.5 x IQR (for the higher upper whisker) respectively. Outliers are represented by points outside of the range of the whisker. The lowest and highest oulier would then mark the minimum/maximum value. For crime rate, the end of the whiskers represent the minimum/maximum value. For unemployment, we find an outlier that represents the maximum of observed values (i.e., Gelsenkirchen with 14.9% unemployment).</p>
<p>Apart from that, the larger the single parts in the boxplot, the greater the dispersion of the data in this area (which can also give an impression of the skewness of the data distribution).</p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">unemp</span>, </span>
<span>        col <span class="op">=</span> <span class="st">'blue'</span>, </span>
<span>        horizontal <span class="op">=</span> <span class="cn">FALSE</span>,</span>
<span>        ylab <span class="op">=</span> <span class="st">'in %'</span>, </span>
<span>        main <span class="op">=</span> <span class="st">'Unemployment rate'</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="../Images/194d9556a8307f91be6421ee44339ed3.png" width="80%" style="display: block; margin: auto;" data-original-src="https://bookdown.org/conradziller/introstatistics/01-univariate_files/figure-html/unnamed-chunk-12-1.png"/></div>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="va">data_nrw</span><span class="op">$</span><span class="va">crimerate</span>, </span>
<span>        col <span class="op">=</span> <span class="st">'orange'</span>, </span>
<span>        horizontal <span class="op">=</span> <span class="cn">FALSE</span>,</span>
<span>        ylab <span class="op">=</span> <span class="st">'in cases per 100.000 inhab.'</span>, </span>
<span>        main <span class="op">=</span> <span class="st">'Crime rate'</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="../Images/57838b3ff7c316b4139a4ef1e0528985.png" width="80%" style="display: block; margin: auto;" data-original-src="https://bookdown.org/conradziller/introstatistics/01-univariate_files/figure-html/unnamed-chunk-12-2.png"/></div>
</div>
<div id="conclusion" class="section level2" number="2.8">
<h2>
<span class="header-section-number">2.8</span> Conclusion<a class="anchor" aria-label="anchor" href="#conclusion"/>
</h2>
<p>The provided examples illustrate some basic principles of univariate descriptive statistics. Univariate statistics are important to get an overview of the structure of the data, which may also inform more complex statistical methods.
In terms of further steps, we could apply the learned methods and ask: Which counties are most plagued by crime? Which counties have the lowest unemployment, and which have the highest? Where are particularly large numbers of people moving to or from?
This may inspire additional questions, like: Why are the observed structures the way they are? These questions concern explanatory analyses. In the following, we take an outlook on this and – by doing so – we refer to further topics that are explained in detail in subsequent chapters.</p>
<p><br/><br/></p>
</div>
<div id="outlook-does-unemployment-cause-more-crime" class="section level2" number="2.9">
<h2>
<span class="header-section-number">2.9</span> Outlook: Does unemployment cause more crime?<a class="anchor" aria-label="anchor" href="#outlook-does-unemployment-cause-more-crime"/>
</h2>
<p>To test causal claims like “more unemployment leads to more crime” with observational data (i.e., from surveys or official records) is heroic and rests on various assumptions that need to be fulfilled. The main reason why causal inference with observational (i.e., non-experimental) data is so difficult is that all possible alternative explanations must be eliminated. Otherwise, we cannot be sure whether unemployment is the cause or some other unobserved phenomenon that correlates with unemployment.</p>
<p>For causal inference, the following three conditions must be met:</p>
<ul>
<li>X (cause) and Y (effect) must be empirically related to each other (e.g., correlate with each other).</li>
<li>X must precede Y in time (e.g., can be mapped with panel data).</li>
<li>Most importantly: All possible alternative explanations must be excluded (e.g., via a randomized experiment or by using control variables in multiple regression).</li>
</ul>
<p>We will revisit these assumptions in the case study on regression analysis.</p>
<p><br/></p>
<div id="bivariate-analysis-correlation" class="section level3" number="2.9.1">
<h3>
<span class="header-section-number">2.9.1</span> Bivariate analysis: Correlation<a class="anchor" aria-label="anchor" href="#bivariate-analysis-correlation"/>
</h3>
<p>A good way to get an impression of the direction of a correlation is using a scatter plot.</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">sc1</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">data_nrw</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">unemp</span>, y <span class="op">=</span> <span class="va">crimerate</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">xlab</span><span class="op">(</span><span class="st">"Unemployment rate 2020 in %"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">ylab</span><span class="op">(</span><span class="st">"Crime rate"</span><span class="op">)</span></span>
<span><span class="va">sc1</span></span></code></pre></div>
<div class="inline-figure"><img src="../Images/079ab43b5a418b983371785f868044a9.png" width="672" data-original-src="https://bookdown.org/conradziller/introstatistics/01-univariate_files/figure-html/unnamed-chunk-13-1.png"/></div>
<p>A line that describes the linear relationship between the two variables can be added:</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">sc1</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">data_nrw</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">unemp</span>, y <span class="op">=</span> <span class="va">crimerate</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_smooth</span><span class="op">(</span>method <span class="op">=</span> <span class="va">lm</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">xlab</span><span class="op">(</span><span class="st">"Unemployment rate in %"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">ylab</span><span class="op">(</span><span class="st">"Crime rate"</span><span class="op">)</span></span>
<span><span class="va">sc1</span></span></code></pre></div>
<div class="inline-figure"><img src="../Images/9d6f6220261bee4f635dcd40dc62ea29.png" width="672" data-original-src="https://bookdown.org/conradziller/introstatistics/01-univariate_files/figure-html/unnamed-chunk-14-1.png"/></div>
<blockquote>
<font size="-1"> <i><strong>Interpretation: The depicted observations and the fitted line imply a positive correlation. (The higher the unemployment rate, the higher the crime rate.)</strong> </i> </font>
</blockquote>
<p><br/></p>
<p>Pearson’s correlation coefficient “r” quantifies the correlation: -1 = perfect neg. correlation, 0 = no correlation, +1 = perfect pos. correlation.</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">vars</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"unemp"</span>, <span class="st">"crimerate"</span><span class="op">)</span></span>
<span><span class="va">cor.vars</span> <span class="op">&lt;-</span> <span class="va">data_nrw</span><span class="op">[</span><span class="va">vars</span><span class="op">]</span></span>
<span><span class="fu">rcorr</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span><span class="op">(</span><span class="va">cor.vars</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##           unemp crimerate
## unemp      1.00      0.72
## crimerate  0.72      1.00
## 
## n= 53 
## 
## 
## P
##           unemp crimerate
## unemp            0       
## crimerate  0</code></pre>
<blockquote>
<font size="-1"> <i><strong>Interpretation: In this case, the correlation coefficient is r = 0.72 with a p-value of &lt; 0.001. That means that we find a strong positive correlation. The correlation is also statistically significant (we typically speak of a statistically significant result if the p-value is below 0.05), which means that we can be fairly certain that the result is not due to chance but can be interpreted as systematic</strong>. </i> </font>
</blockquote>
<p><br/></p>
</div>
<div id="regression-with-control-variables" class="section level3" number="2.9.2">
<h3>
<span class="header-section-number">2.9.2</span> Regression with control variables<a class="anchor" aria-label="anchor" href="#regression-with-control-variables"/>
</h3>
<p>The correlation showed that there is a positive (and statistically significant) bivariate relationship between unemployment and crime. But is this relationship causal? One way to assess this is to control for alternative explanations using multiple regression. We use population density as an alternative explanation. After all, it may well be that unemployment and crime occur primarily in an urban context. If that was the case, part of the correlation would not be due to unemployment, but to population density, and unemployment would so to say partly “transport” the effect of population density (if not included in the regression model). Let’s take a look at this.</p>
<ul>
<li>Model 1 includes unemployment as an explanatory variable</li>
<li>Model 2 includes unemployment <strong>and</strong> population density</li>
</ul>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">model1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">crimerate</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> <span class="va">unemp</span>, data <span class="op">=</span> <span class="va">data_nrw</span><span class="op">)</span></span>
<span><span class="va">model2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">crimerate</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> <span class="va">unemp</span> <span class="op">+</span> <span class="va">popdens</span>, data <span class="op">=</span> <span class="va">data_nrw</span><span class="op">)</span></span>
<span/>
<span><span class="fu">stargazer</span><span class="op">(</span><span class="va">model1</span>, <span class="va">model2</span>, type <span class="op">=</span> <span class="st">"text"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## =================================================================
##                                  Dependent variable:             
##                     ---------------------------------------------
##                                       crimerate                  
##                              (1)                    (2)          
## -----------------------------------------------------------------
## unemp                     517.460***             215.409**       
##                            (69.412)              (100.125)       
##                                                                  
## popdens                                           1.054***       
##                                                   (0.275)        
##                                                                  
## Constant                 2,398.594***           3,513.062***     
##                           (543.248)              (563.493)       
##                                                                  
## -----------------------------------------------------------------
## Observations                  53                     53          
## R2                          0.521                  0.630         
## Adjusted R2                 0.512                  0.615         
## Residual Std. Error  1,240.129 (df = 51)    1,101.398 (df = 50)  
## F Statistic         55.575*** (df = 1; 51) 42.557*** (df = 2; 50)
## =================================================================
## Note:                                 *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<blockquote>
<font size="-1"> <i> <strong>Interpretation: If unemployment increases by one percentage point, crime increases by 517 cases per 100,000 inhabitants (Model 1). The relationship is statistically significant. If we now control for population density in Model 2 (and thus hold the influence of population density constant), a one-unit increase in unemployment is associated with an increase of only 215 cases. Population density is also positively associated with crime. Both coefficient estimates are statistically significant at p &lt; 0.01.
It thus seems to be a good idea to control for the influence of population density. We might be now much closer to the real effect of unemployment on crime now. However, we do not know this for certain because other alternative explanations are still possible to think of (e.g., the role of age composition or local social policies, as well as alternative explanations at the level of individuals)</strong>. </i> </font>
</blockquote>
<hr/>
<p><strong>Disclaimer: If this outlook has been too complex, no worries. We will go through all the steps in detail in the subsequent case studies</strong>.</p>
<hr/>
<p><br/><br/></p>
</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="index.html"><span class="header-section-number">1</span> Preface</a></div>
<div class="next"><a href="bivariate-statistics-case-study-united-states-presidential-election.html"><span class="header-section-number">3</span> Bivariate Statistics – Case Study United States Presidential Election</a></div>
</div>    
</body>
</html>